force-app/main/default/objects/Idea__c/Idea__c.object-meta.xml
<CustomObject>
    <description>Created by BN
BWRD Users
To track BWRD Ideas
Created manually.</description>
    <label>Idea</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Idea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ideas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Idea__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BN
BWRD
To connect an idea to an Account
Populated manually</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ideas</relationshipLabel>
    <relationshipName>Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Competitive_Landscape__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Landscape__c</fullName>
    <description>BN
BWRD
To track an ideas information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Competitive Landscape</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Existing_Options__c.field-meta.xml
<CustomField>
    <fullName>Existing_Options__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Existing Options</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Key_Benefits__c.field-meta.xml
<CustomField>
    <fullName>Key_Benefits__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Key Benefits</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Key_Features__c.field-meta.xml
<CustomField>
    <fullName>Key_Features__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Key Features</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Pain_Points__c.field-meta.xml
<CustomField>
    <fullName>Pain_Points__c</fullName>
    <description>BN
BWRD
To track an ideas information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Pain Points</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Product_Traction__c.field-meta.xml
<CustomField>
    <fullName>Product_Traction__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Traction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Submitter__c.field-meta.xml
<CustomField>
    <fullName>Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>BN
BWRD
To connect an idea to a Contact that submitted it.
Populated manually</description>
    <label>Submitter</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ideas</relationshipLabel>
    <relationshipName>Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>BN
BWRD
To track an ideas information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Target_Market__c.field-meta.xml
<CustomField>
    <fullName>Target_Market__c</fullName>
    <description>BN
BWRD
To track an ideas information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Target Market</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Team</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Idea__c/fields/Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Value_Proposition__c</fullName>
    <description>BN
BWRD User
To track Idea information
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Value Proposition</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/VenturesIdeaSubmissionController.cls
public class VenturesIdeaSubmissionController {

    list<Contact> contactList{get; set;}
    public list<Account> defaultAccountId{get; set;}
    public contact submitter{get; set;}
    public string submitterFirstName{get; set;}
    public string submitterLastName{get; set;}
    public string submitterEmail{get; set;}
    public string submitterPhone{get; set;}

    public string ideaName{get; set;}
    public string ideaSummary{get; set;}
    public string ideaTargetMarket{get; set;}
    public string ideaCompetitiveLandscape{get; set;}
    public string ideaPainPoints{get; set;}
    public string ideaValueProposition{get; set;}
    public string ideaExistingOptions{get; set;}
    public string ideaKeyFeatures{get; set;}
    public string ideaKeyBenefits{get; set;}
    public string ideaProductTraction{get; set;}
    public string ideaTeam{get; set;}


    public PageReference submitIdea() {
       	//List<contact> contactList = new List<contact>();
        contactList = [SELECT Id, AccountId FROM Contact WHERE email = :submitterEmail];

        if(contactList.size()>0) {
            submitter = contactList[0];
        } else {
            submitter = createNewContact();
        }
        insertIdea();
        PageReference pageRef = new PageReference('/apex/VenturesIdeaConfirmation');
        pageRef.setRedirect(true);
        return pageRef;
    }

    public void insertIdea() {
        Idea__c idea = new Idea__c (
            Submitter__c = submitter.Id,
            Account__c = submitter.AccountId,
            Name = ideaName,
            Summary__c = ideaSummary,
            Target_Market__c = ideaTargetMarket,
            Competitive_Landscape__c = ideaCompetitiveLandscape,
            Pain_Points__c = ideaPainPoints,
            Value_Proposition__c = ideaValueProposition,
            Existing_Options__c = ideaExistingOptions,
            Key_Features__c = ideaKeyFeatures,
            Key_Benefits__c = ideaKeyBenefits,
            Product_Traction__c = ideaProductTraction,
            Team__c = ideaTeam
        );
        insert idea;
        system.debug('Idea Submitted');
    }

    public Contact createNewContact() {
        
        Id IndividualRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId();
		defaultAccountId = [SELECT Id FROM Account WHERE RecordType.Id = :IndividualRecordTypeId]; 
        Contact newContact = new Contact (
            AccountId = defaultAccountId[0].Id,
            firstName = submitterFirstName,
            lastName = submitterLastName,
            email = submitterEmail,
            MobilePhone = submitterPhone
        );
        insert newContact;
        system.debug('Contact Created, Idea Submitted');
        return newContact;
    }
}