force-app/main/default/objects/Apprenticeship__c/Apprenticeship__c.object-meta.xml
<CustomObject>
    <label>Apprenticeship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Apprenticeship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apprenticeships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprenticeship__c/fields/Apprentice_Pathway__c.field-meta.xml
<CustomField>
    <fullName>Apprentice_Pathway__c</fullName>
    <description>Created By: RS
Purpose: Apprenticeship dashboard build.</description>
    <label>Apprentice Pathway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Apprentice_Pathway</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/Apprenticeship_Lead__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT
Keeps track of the Lead of this Apprenticeship.</description>
    <label>Apprenticeship Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprenticeships (Lead)</relationshipLabel>
    <relationshipName>Apprenticeships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created by JW
Business Unit: WFT
Keeps track of when this Apprenticeship ends.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created by JW
Business Unit: WFT
Keeps track of the date this Apprenticeship begins.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created by JW
Business Unit: WF
Keeps track of this Apprenticeship&apos;s status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/Tech_Stack__c.field-meta.xml
<CustomField>
    <fullName>Tech_Stack__c</fullName>
    <description>GS
Purpose: For WFT Apprenticeship Dashboard.</description>
    <label>Tech Stack</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Apprentice_Pathway__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Apprentice_Tech_Stack</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Co_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Co_Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Relates a Contact record as a Co=Teacher for the Class
Populated: Manual</description>
    <label>Co-Teacher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Co-Teacher)</relationshipLabel>
    <relationshipName>Classes_CoTaught</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>CC For Displaying a simplified name on the website</description>
    <formula>IF(ISPICKVAL(Class__c, &apos;Other&apos;), Other__c, TEXT(Class__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For Displaying a Simplified Name on the website</inlineHelpText>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Relates a Contact record as an Instructor for this class
Populated: Manual</description>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Qualified_Instructor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Instructor)</relationshipLabel>
    <relationshipName>Classes_Instructed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Num_Students_Registered__c.field-meta.xml
<CustomField>
    <fullName>Num_Students_Registered__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Counts the number of registrations related to a singe Class record
Populated: Auto, Roll-Up Summary</description>
    <label># Students Registered</label>
    <summaryFilterItems>
        <field>Registration__c.Dropped__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Registration__c.Dropped_w_Credit__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Registration__c.Class__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Scheduled_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Time__c</fullName>
    <label>Scheduled Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6:00pm - 9:00pm</fullName>
                <default>true</default>
                <label>6:00pm - 9:00pm</label>
            </value>
            <value>
                <fullName>6:00pm - 9:00pm Eastern Time</fullName>
                <isActive>false</isActive>
                <label>6:00pm - 9:00pm Eastern Time</label>
            </value>
            <value>
                <fullName>6:00pm - 9:00pm Pacific Time</fullName>
                <isActive>false</isActive>
                <label>6:00pm - 9:00pm Pacific Time</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: AF; Business Unit: Geekwise Users; Purpose: Updates Class Status based on Start and End date; Populated: Auto via Formula</description>
    <formula>IF( Start_Date__c &gt; TODAY(), &apos;Upcoming&apos;, 
IF( End_Date__c &lt; TODAY(), &apos;Past&apos;, &apos;Active&apos; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teachers_Assistant__c.field-meta.xml
<CustomField>
    <fullName>Teachers_Assistant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Links a Contact as a TA for this Class
Populated: Manual</description>
    <inlineHelpText>The TA for this course (This is a PAID position)</inlineHelpText>
    <label>Teacher&apos;s Assistant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Teacher&apos;s Assistant)</relationshipLabel>
    <relationshipName>Class_TA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>RS</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WFTPortalHomeController.cls
public class WFTPortalHomeController {
	public List<Class__c> classes { get; set; }
  	public List<Apprenticeship__c> apprenticeships { get; set; }
  	String dayFormat = 'MM/DD';
  	public String recordId {get; set; }
  	private User currentUser;
  	public Profile userProfile;
  	public Boolean  showApprenticeships {get;set;}
   	public Boolean showClasses {get;set;}
  	public List<Profile> seeAllClassesProfiles;
  
  	public WFTPortalHomeController() {
    	currentUser = [SELECT Id, Name, Email, ContactId FROM User WHERE Id =: UserInfo.getUserId()];
    
		userProfile = [SELECT Id, Name
					   FROM Profile
                   	   WHERE Id = : UserInfo.getProfileId()]; 
    
    	seeAllClassesProfiles = new List<Profile>();
    	seeAllClassesProfiles = [SELECT Id, Name
                             	 FROM Profile
							 	 WHERE Name = 'WFT User'
							 	 OR Name = 'System Administrator'
							 	 OR Name = 'BW System Admin'
							  	 OR Name = 'BW Executive'];

    	System.debug(seeAllClassesProfiles);
    	getClasses();
    	getApprenticeships();
  	}
  
	public void getClasses() {
	  	// Determine if WFT Community User or if Allowed to See all Classes
	  	if (seeAllClassesProfiles.contains(userProfile)) {
		  	classes = [SELECT Id, Display_Name__c, Class_Nights__c, Start_Date__c, End_Date__c, 
                       Scheduled_Time__c, Time_Zone__c, Instructor__r.Name
		  			   FROM Class__c WHERE Start_Date__c <= :System.today().addDays(7) 
                       AND End_Date__c >= :System.today().addDays(-7) 
                       AND Num_Students_Registered__c > 0
                       ORDER BY Display_Name__c, Start_Date__c];
		  	
		  	showClasses = !classes.isEmpty();
		  	return;
      	} 
      
		if (!String.isBlank(currentUser.ContactId)) {
			classes = [SELECT Id, Display_Name__c, Class_Nights__c, Start_Date__c, End_Date__c, 
                       Scheduled_Time__c, Time_Zone__c, Instructor__r.Name
		  			   FROM Class__c WHERE Start_Date__c <= :System.today().addDays(7) 
                       AND End_Date__c >= :System.today().addDays(-7) 
                       AND Num_Students_Registered__c > 0
					   AND (Instructor__c = :currentUser.ContactId
					   OR Co_Teacher__c = :currentUser.ContactId
					   OR Teachers_Assistant__c = :currentUser.ContactId)
					   ORDER BY Display_Name__c, Start_Date__c];
			
			showClasses = !classes.isEmpty();
			return;
		}

		classes = [SELECT Id, Display_Name__c, Class_Nights__c, Start_Date__c, End_Date__c, 
                   Scheduled_Time__c, Time_Zone__c, Instructor__r.Name
		  		   FROM Class__c WHERE Start_Date__c <= :System.today().addDays(7) 
                   AND End_Date__c >= :System.today().addDays(-7) 
                   AND Num_Students_Registered__c > 0
				   AND (Instructor__r.Email = :currentUser.Email
				   OR Co_Teacher__r.Email = :currentUser.Email
				   OR Teachers_Assistant__r.Email = :currentUser.Email)
				   ORDER BY Display_Name__c, Start_Date__c];
					
		
		showClasses = !classes.isEmpty();
	}

	public void getApprenticeships() {
		// Determine if WFT Community User or if Allowed to See all Apprenticeships
		
		if ( seeAllClassesProfiles.contains(userProfile)) {
			apprenticeships = [SELECT Id, Name, Start_Date__c, End_Date__c, 
                               Apprentice_Pathway__c, Tech_Stack__c, Apprenticeship_Lead__r.Name 
							   FROM Apprenticeship__c
							   WHERE status__c != 'Inactive'
							   ORDER BY Name];
	
			showApprenticeships = !apprenticeships.isEmpty();
			return;
		} 
		if (!String.isBlank(currentUser.ContactId)) {
			apprenticeships = [SELECT Id, Name, Start_Date__c, End_Date__c,
                               Apprentice_Pathway__c, Tech_Stack__c, Apprenticeship_Lead__r.Name
							   FROM Apprenticeship__c
							   WHERE status__c != 'Inactive'
							   AND Apprenticeship_Lead__c = :currentUser.ContactId
							   ORDER BY Name];
			
            showApprenticeships = !apprenticeships.isEmpty();	
			return;
		}

		apprenticeships = [SELECT Id, Name, Start_Date__c, End_Date__c,
                           Apprentice_Pathway__c, Tech_Stack__c, Apprenticeship_Lead__r.Name
						   FROM Apprenticeship__c
						   WHERE status__c != 'Inactive'
						   AND Apprenticeship_Lead__r.Email = :currentUser.Email
						   ORDER BY Name];
		
        showApprenticeships = !apprenticeships.isEmpty();
		
	}

  public Pagereference toClassRoster() {

    String url = '/apex/WFTClassRoster?id=' + recordId;
    return new PageReference(url);
  }

  public Pagereference toApprenticeshipRoster() {

    String url = '/apex/WFTApprenticeshipRoster?id=' + recordId;
    return new PageReference(url);
  }
}