force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>CC Hashtag End date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC Hashtag Link Space to Reservation Visualforce</description>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>CC Hashtag Start date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Calendar_ID__c.field-meta.xml
<CustomField>
    <fullName>Calendar_ID__c</fullName>
    <description>JA
Business Unit: Hashtag
Purpose: Store Related Google Calendar Id
Population: Manual</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Calendar ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GoogleCalendarReservationBatch.cls
public class GoogleCalendarReservationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    public Set<Id> reservationIds;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.assertNotEquals(null, reservationIds, 'reservationIds in GoogleCalendarReservationBatch is null.');

        String query = 'SELECT Id, Space__r.Calendar_Id__c, Contact__r.Name, Start__c, End__c FROM Reservation__c WHERE Id IN :reservationIds';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Reservation__c> reservations) {
        for (Reservation__c res : reservations) {
            GoogleCalendarService.getInstance().createCalendarEvent(res.Space__r.Calendar_Id__c, res.Start__c, res.End__c, res.Contact__r.Name);
        }
    }

    public void finish(Database.BatchableContext BC) {}
}