force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>CC Hashtag End date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC Hashtag Link Space to Reservation Visualforce</description>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>CC Hashtag Start date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>There&apos;s a known issue about DATEVALUE() with times near midnight:
https://success.salesforce.com/issues_view?id=a1p30000000Su0tAAC</description>
    <formula>DATEVALUE(Start__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Calendar_Link__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Link__c</fullName>
    <formula>&quot;https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FLos_Angeles&amp;src=&quot; &amp; Calendar_Source_Id__c  
    &amp; &quot;&amp;color=%2322AA99&amp;mode=day&amp;showCalendars=0&amp;showTabs=0&amp;showTitle=1&amp;showNav=1&amp;showPrint=0&amp;dates=&quot; &amp; Calendar_Date__c &amp; &quot;/&quot; &amp; Calendar_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calendar Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Space__c/fields/Reservation_Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Room_Type__c</fullName>
    <description>Created By: DA
Business Unit: Hashtag
Purpose: Defines the type of reservation space</description>
    <label>Reservation Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference Room</fullName>
            </value>
            <value>
                <fullName>Podcast Booth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TabletReservation.cls
public class TabletReservation {
    public string currentRoomId{get;set;}
    public space__c currentRoom{get;set;}
    // public list<Reservation__c> roomReservations{get;set;}
    public date getToday{get;set;}
    // public string formatedDate{get;set;}
    public List<Reservation__c> currentReservation{get;set;}
    public dateTime currentTime{get;set;}
    public Reservation__c printReservation{get;set;}


    public TabletReservation() {
        getToday = date.today();
        currentRoomId = apexpages.currentPage().getparameters().get('Id');
        getRoomInfo(currentRoomId);
        currentTime = System.now();
        // printReservation = checkCurrentReservation();
    }

    public void getRoomInfo(Id roomId) {
        // try{
            currentRoom = [SELECT Id, Name, Calendar_Link__c, Reservation_Room_Type__c FROM Space__c WHERE Id = :roomId ];
        // roomReservations = [SELECT id, name, start__c, end__c, contact__r.name FROM reservation__c WHERE space__c = :currentRoomId AND start_date__c = :getToday AND start__c > :System.now() ORDER BY start__c ASC];
        // } catch(QueryException e) {
        //     // Apexpages.addMessages(e);
        //     // testString = 'Hello from the catch block';

        // }        
    }

    // public Reservation__c checkCurrentReservation() {
    //     currentReservation = [SELECT id, name, start__c, end__c, contact__r.name FROM reservation__c WHERE space__c = :currentRoomId AND start_date__c = :getToday AND start__c <= :System.now() AND end__c > :System.now() LIMIT 1];
    //     if(currentReservation.size() > 0) {
    //         return currentReservation[0];
    //     } else {
    //         return null;
    //     }

    // }
}