force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: YB
Business Unit: BTC
Purpose: The status of the Project.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal Kickoff</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Project Complete</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: MH
Business Unit: BTC
Purpose: The type of Project i.e. SFDC or Custom Dev</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Dev</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>Wordpress Cohort</fullName>
            </value>
            <value>
                <fullName>Onward</fullName>
            </value>
            <value>
                <fullName>Take Care</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Municipal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/LDA.recordType-meta.xml
<RecordType>
    <fullName>LDA</fullName>
    <active>true</active>
    <label>LDA</label>
</RecordType>

force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Project Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: CC
Purpose: indicate Project Members Status on a Project</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectEndpoint.cls
@RestResource(urlMapping='/projects/*')
global class ProjectEndpoint {
    @HttpGet
    global static ProjectResult getProjectResults() {
       	RestRequest req = RestContext.request;
		System.debug(req);
		System.debug(req.params);
        Map<String, String> params = req.params;
        String projectId = params.get('project');
        String contactEmail = params.get('contact');
		
		if(!String.isBlank(contactEmail)) {
			contactEmail = EncodingUtil.urlDecode(contactEmail, 'UTF-8');

			return getProjectsByMember(contactEmail, projectId);
		}

		ProjectResult res = new ProjectResult();
		res.Error_Code = 'CONTACT_EMAIL_MUST_BE_PROVIDED';
		res.message = 'Must provide a Contact email.';
		RestContext.response.statusCode = 400;
		return res;
    }

    
    public static ProjectResult getProjectsByMember(String contactEmail, String projectId) {
		ProjectResult res = new ProjectResult();
        List<Project__c> projects = new List<Project__c>();
		List<Project_Member__c> projectMembers = new List<Project_Member__c>();

		List<Id> projectIds = new List<Id>();

		contactEmail = String.escapeSingleQuotes(contactEmail);
        //CC (3/14/22) Added a check for recordType so only LDA projects are returned.
		String projectRecordTypeId = Schema.SObjectType.Project__c.getRecordTypeInfosByName().get('LDA').getRecordTypeId();
        
        if(String.isBlank(projectId)) {
			projectMembers = [SELECT Id, Project__c FROM Project_Member__c
							  WHERE Contact__r.Email = :contactEmail AND Contact__r.LDA_Time_Tracking__c = true AND
							  Project__r.Status__c != 'Archived' AND Project__r.RecordTypeId = :projectRecordTypeId AND Status__c = 'Active'];
		}
		else {
			projectId = String.escapeSingleQuotes(projectId);
			projectMembers = [SELECT Id, Project__c FROM Project_Member__c 
						      WHERE Contact__r.Email = :contactEmail AND Contact__r.LDA_Time_Tracking__c = true AND
						  	  Project__c = :projectId AND Project__r.RecordTypeId = :projectRecordTypeId AND Project__r.Status__c != 'Archived' 
							  AND Status__c = 'Active'];
		}
	

		if( projectMembers.isEmpty()) {
			res.Error_Code = 'PROJECT_MEMBER_NOT_FOUND';
			res.message = 'Must have LDA extension access and Must be an active project member on a non archived project.';
			RestContext.response.statusCode = 404;
			return res;
		}

		for(Project_Member__c pm : projectMembers) {
			if(!projectIds.contains(pm.Project__c)) {
				projectIds.add(pm.Project__c);
			}
		}

		projects = [SELECT Id, Name, Status__c, RecordTypeId, Type__c
					FROM Project__c 
					WHERE Id IN :projectIds ORDER BY Id];

		System.debug('Projects: '+ projects.size() + ' Project Members: ' + projectMembers.size());
		return createProjectResult(projects);

    }

	public static ProjectResult createProjectResult(List<Project__c> projects) {
		ProjectResult res = new ProjectResult();
		Integer numberOfProjects = 0;
		Map<String,String> recordTypes = new Map<String, String>();
		for(Project__c project : projects) {
            Project singleResult = new Project();
			String recordType;

			singleResult.Id = project.Id;
			singleResult.Name = project.Name;
			singleResult.Status = project.Status__c;

			// FV (8/23/21) 
			// If project has record type, then return it as part of project data
			if (!String.isBlank(project.recordTypeId)) {
				if (recordTypes.containsKey(project.recordTypeId)) {
					singleResult.RecordType = recordTypes.get(project.recordTypeId);
				}
				else {
					String recordTypeName;
					recordTypeName = Schema.SObjectType.Project__c.getRecordTypeInfosById().get(project.recordTypeId).getName();
					
					if(!String.isBlank(recordTypeName)) {
						recordTypes.put(project.RecordTypeId, recordTypeName);
						singleResult.RecordType = recordTypes.get(project.recordTypeId);
						
					}
					
				}
			}

			// FV (8/31/21) 
			// If project has type, then return it as part of project data
			if (!String.isBlank(project.Type__c)) {
				singleResult.Type = project.Type__c;
			}

		
			numberOfProjects++;
			System.debug(SingleResult);
			res.projects.add(singleResult);
		}

		System.debug('Projects: '+ projects.size());
		res.Number_Of_Projects = numberOfProjects;
        return res;
	}


	global class Project {
        public Id Id;
		public String Name;
        public String Status;
		public String RecordType; // FV (8/23/21) - Added this to allow dynamic chrome extension options
		public String Type; // FV (8/31/21) - Added this to allow dynamic chrome extension options
    }

	global class ProjectResult {
		 public Integer Number_Of_Projects = 0;
		 public List<Project> Projects = new List<Project>();
         public String Message;
		 public String Error_Code; 
	}
}