force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Created By: MH
Business Unit: BTC-PM
Purpose: Description of the project.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: YB
Business Unit: BTC
Purpose: The status of the Project.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal Kickoff</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Project Complete</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: MH
Business Unit: BTC
Purpose: The type of Project i.e. SFDC or Custom Dev</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Dev</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>Wordpress Cohort</fullName>
            </value>
            <value>
                <fullName>Onward</fullName>
            </value>
            <value>
                <fullName>Take Care</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Municipal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Project Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: CC
Purpose: indicate Project Members Status on a Project</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Track time of projects.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Connect Contact to Time Entry.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Created By: CC
Department: BW
Purpose: Date of Time Entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Description of Time Entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Created By: CC
Department: BW
Purpose: Hours/Time recorded.</description>
    <label>Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Project of Time Entry.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: FV
Department: BW
Purpose: Allows the Time Entry objects to have extra types if needed (i.e. for LDA the time entry can be either federal or non-profit).</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bitwise (Company)</fullName>
            </value>
            <value>
                <fullName>Bitwise Impact (Nonprofit)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TimeEntryEndpoint.cls
@RestResource(urlMapping='/time_entry/*')
global class TimeEntryEndpoint {
	@HttpGet
    global static TimeEntryResult getTimeEntry() {
        RestRequest req = RestContext.request;
        Map<String, String> params = req.params;
        TimeEntryResult res  = new TimeEntryResult();

        String projectId = params.get('project');
        String contactEmail = params.get('contact');
		if(!String.isBlank(contactEmail)) {
			contactEmail = EncodingUtil.urlDecode(contactEmail, 'UTF-8');
		}
        else {

            res.Error_Code = 'CONTACT_EMAIL_MUST_BE_PROVIDED';
			res.message = 'Must provide a Contact email.';
			RestContext.response.statusCode = 400;
			return res;
        }
        List<String> fieldNames = new List<String> {
			'Id', 
            'Contact__c', 
            'Contact__r.Name',
			'Contact__r.Email', 
            'Hours__c', 
            'Description__c',
			'Date__c',
			'Project__r.Name',
			'Project__r.Type__c'
		};
        
        List<String> optWhereClauses = new List<String>();
        
        Boolean projectAndContact = !String.isBlank(projectId) && !String.isBlank(contactEmail);

        String whereClause = '';
        if(projectAndContact) {
            whereClause = 'Project__c = :projectId AND Contact__r.Email = :contactEmail';
        }
        else {
            
            if(!String.isBlank(contactEmail)) {
                whereClause = 'Contact__r.Email = :contactEmail AND Date__c >= LAST_N_DAYS:29';
            }
        }
       
        String query = 'SELECT ' + String.join(fieldNames,',') + ' FROM Time_Entry__c';
        
        if(!String.isBlank(whereClause)) {
            query += ' WHERE ' + whereClause;
        } 

        query += ' ORDER BY Date__c DESC LIMIT 50';

        
		try {
			res.Time_Entry_Records = (List<Time_Entry__c>) Database.query(query);
        	res.Number_Of_Time_Records = res.Time_Entry_Records.size();
		} catch (Exception ex) {
			System.debug('QUERY_FAILED');
			res.Error_Code = 'QUERY_FAILED';
			res.message = ex.getMessage();
		}
        
        return res;
    }

	@HttpPost
	global static TimeEntryResult postTimeEntry() {
		RestRequest req = RestContext.request;
		TimeEntryResult res = new TimeEntryResult();

		String body = req.requestBody.toString();

        Map<String, Object> params =  (Map<String, Object>) JSON.deserializeUntyped(body);

		Boolean RequiredValuesFound = params.containsKey('contact')  && params.containsKey('project') 
                                      && params.containsKey('hours');
		
		if (!RequiredValuesFound) {
			res.Error_Code = 'REQUIRED_FIELD_MISSING';
			res.message = 'Body must include values for contact, project, and hours.';
			RestContext.response.statusCode = 400;
			return res;
		}
		Decimal timeInput = Decimal.valueOf((String)params.get('hours'));
		if (timeInput <= 0) {
			res.Error_Code = 'BAD_PARAMETER';
			res.message = 'Hours must be greater than zero.';
			RestContext.response.statusCode = 400;
			return res;
		}

		
		String contactEmail = String.escapeSingleQuotes((String) params.get('contact'));
		String projectId = String.escapeSingleQuotes((String) params.get('project'));
		
		List<Project_Member__c> projectMember = new List<Project_Member__c>();

		projectMember = [SELECT Id, Contact__c FROM Project_Member__c 
							WHERE Project__c = :projectId AND 
							Project__r.Status__c != 'Archived' AND
							Contact__r.Email = :contactEmail AND 
							Status__c = 'Active'];

		if(projectMember.isEmpty()) {
			res.Error_Code = 'PROJECT_MEMBER_NOT_FOUND';
			res.message = 'Must be an active project member on an non archived project to submit time.';
			RestContext.response.statusCode = 404;
			return res;
		}

		Date timeDate = System.today();
		if (params.containsKey('date')) {
			System.debug(params.get('date'));
			timeDate = Date.valueOf((String) params.get('date'));
		}

		String entryType = '';
		if (params.containsKey('type')) {
			entryType = String.escapeSingleQuotes((String) params.get('type'));
		}


		Time_Entry__c timeEntryRecord = new Time_Entry__c(Id = (String)params.get('id'), 
											Contact__c = projectMember[0].Contact__c, 
											Project__c = projectId,
											Date__c = timeDate,
											Hours__c = timeInput,
											Type__c = entryType,
											Description__c = (String)params.get('description'));
		
		try {
			upsert timeEntryRecord;
		} catch (Exception ex) {
			res.Error_Code = 'INSERT_OR_UPDATE_FAILED';
			res.message = ex.getMessage();
			RestContext.response.statusCode = 400;
			return res;
		}
		res.Time_Entry_Records.add(timeEntryRecord);
		res.Number_Of_Time_Records = 1;
		RestContext.response.statusCode = 201;
		return res;
	
	}

	@HttpDelete
	global static TimeEntryResult deleteTimeEntry() {
		RestRequest req = RestContext.request;
		TimeEntryResult res = new TimeEntryResult();

        Map<String, String> params =  req.params;

		Boolean RequiredValuesFound = params.containsKey('Id');
		
		if (!RequiredValuesFound) {
			res.Error_Code = 'REQUIRED_FIELD_MISSING';
			res.message = 'Id is a required parameter.';
			RestContext.response.statusCode = 400;
			return res;
		}

		String timeEntryId = String.escapeSingleQuotes(params.get('Id'));

		try {
			Time_Entry__c t = new Time_Entry__c(Id = timeEntryId);
			delete t;
		} catch (Exception ex) {
			res.Error_Code = 'DELETE_FAILED';
			res.message = ex.getMessage();
			RestContext.response.statusCode = 400;
			return res;
		}
		res.Number_Of_Time_Records = 1;
		res.Message = 'Record deleted.';
		RestContext.response.statusCode = 200;
		return res;

	}
	global class TimeEntryResult {
		 public Integer Number_Of_Time_Records = 0;
		 public List<Time_Entry__c> Time_Entry_Records = new List<Time_Entry__c>();
		 public String Message;
		 public String Error_Code; 
	}
}