force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: YB
Business Unit: BTC
Purpose: Account Look-Up</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: YB
Business Unit: BTC
Purpose: The status of the Project.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Internal Kickoff</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Ready for Development</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Project Complete</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: MH
Business Unit: BTC
Purpose: The type of Project i.e. SFDC or Custom Dev</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Custom Dev</fullName>
            </value>
            <value>
                <fullName>SFDC</fullName>
            </value>
            <value>
                <fullName>Wordpress Cohort</fullName>
            </value>
            <value>
                <fullName>Onward</fullName>
            </value>
            <value>
                <fullName>Take Care</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Municipal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/LDA.recordType-meta.xml
<RecordType>
    <fullName>LDA</fullName>
    <active>true</active>
    <label>LDA</label>
</RecordType>

force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Project Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: CC
Purpose: indicate Project Members Status on a Project</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Track time of projects.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Connect Contact to Time Entry.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Created By: CC
Department: BW
Purpose: Date of Time Entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Created By: CC
Department: BW
Purpose: Hours/Time recorded.</description>
    <label>Hours</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Project of Time Entry.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: FV
Department: BW
Purpose: Allows the Time Entry objects to have extra types if needed (i.e. for LDA the time entry can be either federal or non-profit).</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bitwise (Company)</fullName>
            </value>
            <value>
                <fullName>Bitwise Impact (Nonprofit)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectEndpointTests.cls
@isTest
public class ProjectEndpointTests {
     @TestSetup
    static void setup() {

        Account a1 = new Account(Name = 'Test Account');
        insert a1;

        Contact contact1 = new Contact(AccountId = a1.Id, LDA_Time_Tracking__c = true, FirstName = 'Test', LastName = 'Contact', Email = 'testcontact@salesforce.com');
        insert contact1;

        Contact contact2 = new Contact(AccountId = a1.Id, LDA_Time_Tracking__c = true, FirstName = 'Test', LastName = 'Contact2', Email = 'testcontact2@salesforce.com');
        insert contact2;

        Project__c project1 = new Project__c(Name = 'Project 1', Status__c = 'Active', Account__c = a1.Id, RecordTypeId = Schema.SObjectType.Project__c.getRecordTypeInfosByName().get('LDA').getRecordTypeId(), Type__c = 'State');
        insert project1;

        Project_Member__c pMember = new Project_Member__c(Project__c = project1.Id, Contact__c = contact1.Id, Status__c = 'Active');
        insert pMember;

        Time_Entry__c time1 = new Time_Entry__c(Contact__c = contact1.Id, Project__c = project1.Id, Hours__c = 1, Date__c = System.today());
        insert time1;

        Time_Entry__c time2 = new Time_Entry__c(Contact__c = contact1.Id, Project__c = project1.Id, Hours__c = .75, Date__c = System.today());
        insert time2;

        Time_Entry__c time3 = new Time_Entry__c(Contact__c = contact2.Id, Project__c = project1.Id, Hours__c = 1.5, Date__c = System.today() - 1);
        insert time3;


        Project__c project2 = new Project__c(Name = 'Project 2', Status__c = 'Active', Account__c = a1.Id);
        insert project2;

        Time_Entry__c time4 = new Time_Entry__c(Contact__c = contact2.Id, Project__c = project2.Id, Hours__c = 1, Date__c = System.today());
        insert time4;

        Time_Entry__c time5 = new Time_Entry__c(Contact__c = contact1.Id, Project__c = project2.Id, Hours__c = .75, Date__c = System.today());
        insert time5;

        Project_Member__c pMember2 = new Project_Member__c(Project__c = project2.Id, Contact__c = contact2.Id, Status__c = 'Active');
        insert pMember2;

    }
    @isTest
    public static void testGetProjectsBadParameters() {
        
       	RestRequest request = new RestRequest();
        request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/projects';
        request.httpMethod = 'GET';

        RestContext.request = request;
        RestContext.response =  new RestResponse();
        ProjectEndpoint.ProjectResult pResult = ProjectEndpoint.getProjectResults();
        System.AssertEquals('CONTACT_EMAIL_MUST_BE_PROVIDED',pResult.Error_Code);
    }
    @isTest
    public static void testGetProjectsFromContact() {
        Contact c = [SELECT Id, Email FROM Contact WHERE LastName = 'Contact'];
       	RestRequest request = new RestRequest();
        request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/projects';
        request.httpMethod = 'GET';
        request.params.put('contact', c.Email);
        RestContext.request = request;
        RestContext.response =  new RestResponse();
        ProjectEndpoint.ProjectResult pResult = ProjectEndpoint.getProjectResults();
        System.AssertEquals(1,pResult.Number_Of_Projects);
    }
    @isTest
    public static void testGetProjectsFromContactAndProjectId() {
        Contact c = [SELECT Id, Email FROM Contact WHERE LastName = 'Contact'];
        Project_Member__c pMember = [SELECT Id, Project__c FROM Project_Member__c
                                     WHERE Contact__c =: c.Id LIMIT 1];
       	RestRequest request = new RestRequest();
        request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/projects';
        request.httpMethod = 'GET';
        request.params.put('contact', c.Email);
        request.params.put('project', pMember.Project__c);
        RestContext.request = request;
        RestContext.response =  new RestResponse();
        ProjectEndpoint.ProjectResult pResult = ProjectEndpoint.getProjectResults();
        System.AssertEquals(1,pResult.Number_Of_Projects);
    }
    @isTest
    public static void testGetProjectsFromContactNonProjectMember() {
        
       	RestRequest request = new RestRequest();
        request.requestUri = 'https://yourInstance.salesforce.com/services/apexrest/projects';
        request.httpMethod = 'GET';
        request.params.put('contact', 'notapm@notapm.com');
        RestContext.request = request;
        RestContext.response =  new RestResponse();
        ProjectEndpoint.ProjectResult pResult = ProjectEndpoint.getProjectResults();
        System.AssertEquals('PROJECT_MEMBER_NOT_FOUND',pResult.Error_Code);
    }
   
}