force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>Created by BN
For: Geekwise User
Function: Track student attendance in classes. Could be used for events later.
Populated by: User either manually or through Instructor Portal.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <description>Created By: RS
Business Unit: Look-up
Purpose: To Track</description>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>CC For Displaying a simplified name on the website</description>
    <formula>IF(ISPICKVAL(Class__c, &apos;Other&apos;), Other__c, TEXT(Class__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For Displaying a Simplified Name on the website</inlineHelpText>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Dropped__c.field-meta.xml
<CustomField>
    <fullName>Dropped__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Indicates if a student has dropped from a class with no credit
Populated: Manual</description>
    <inlineHelpText>Registrant has dropped from the class without credit</inlineHelpText>
    <label>Dropped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Dropped_w_Credit__c.field-meta.xml
<CustomField>
    <fullName>Dropped_w_Credit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Indicates that a student has dropped from a class and received credit for a future class
Populated: Manual</description>
    <inlineHelpText>Registrant has dropped from the class, and received credit for a future class</inlineHelpText>
    <label>Dropped w/Credit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Links the Registration record to a Contact
Populated: Manual/Auto with Web form</description>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Class Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/Student_Engagement__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Student Interactions, Volunteering, etc.</description>
    <label>Student Engagement</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Student Engagement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Engagement__c/fields/Engagement_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Notes__c</fullName>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy employees
Populated: Manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/fields/Engagement_Type__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Type__c</fullName>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy employees
Populated: Manually</description>
    <label>Engagement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One on One</fullName>
            </value>
            <value>
                <fullName>Volunteered</fullName>
                <label>Volunteering</label>
            </value>
            <value>
                <fullName>Cohort Recommendation</fullName>
            </value>
            <value>
                <fullName>Apprenticeship Recommendation</fullName>
            </value>
            <value>
                <fullName>Counseling</fullName>
            </value>
            <value>
                <fullName>Resume Submitted</fullName>
            </value>
            <value>
                <fullName>Professional Development</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Nomination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy students
Populated: Manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Engagements (Student)</relationshipLabel>
    <relationshipName>Student_Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/fields/WFT_Staff_Member__c.field-meta.xml
<CustomField>
    <fullName>WFT_Staff_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: JA
Purpose: To track who had student engagements with Workforce Training students</description>
    <label>WFT Staff Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Engagements (WFT Staff Member)</relationshipLabel>
    <relationshipName>Student_Engagements2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WFTClassRosterController.cls
public class WFTClassRosterController {
  //Class Information
  public Id classId { get; set; }
  public String className { get; set; }

  public Date selectedDate { get; set; }

  public List<Registration__c> registrations { get; set; }
  public List<RosterRowWrapper> rosterRows { get; set; }

  public Id studentId { get; set; }
  public String studentName { get; set; }

  // Notes
  public boolean displayNotes { get; set; }
  public String notesType { get; set; }
  public String notes { get; set; }
  public Student_Engagement__c studentEngagement { get; set; }

  @testVisible
  private String currentUserContactId;

  public WFTClassRosterController() {
    rosterRows = new List<RosterRowWrapper>();
    classId = apexpages.currentPage().getparameters().get('Id');
    selectedDate = System.today();
    getUserContactId();
    getRegistrations();
  }

  public Attendance__c createAttendance(
    Id attendanceId,
    Id registrationId,
    Id studentId,
    Boolean present
  ) {
    Attendance__c attRec = new Attendance__c(
      Registration__c = registrationId,
      Student__c = studentId,
      Date__c = selectedDate,
      Present__c = present
    );

    if (String.isNotBlank(attendanceId)) {
      attRec.Id = attendanceId;
    }

    return attRec;
  }

  public void getRegistrations() {
    rosterRows.clear();
    if (selectedDate == null) {
      return;
    }
    registrations = [
      SELECT
        Id,
        Registrant__c,
        Registrant__r.Name,
        Registrant__r.Slack_Image__c,
        Registrant__r.Pronouns__c,
        Registrant__r.GitHub_Username__c,
        Class__r.Display_Name__c,
        (
          SELECT
            Id,
            Student__c,
            Student__r.Name,
            Student__r.LastName,
            Date__c,
            Present__c
          FROM Attendances__r
          WHERE
            Registration__r.Class__c = :classId
            AND Date__c = :selectedDate
            AND Registration__r.Dropped__c = FALSE
            AND Registration__r.Dropped_w_Credit__c = FALSE
        )
      FROM Registration__c
      WHERE
        Class__r.Id = :classId
        AND Dropped__c = FALSE
        AND Dropped_w_Credit__c = FALSE
    ];

    if (registrations.size() <= 0) {
      return;
    }
    className = registrations[0].Class__r.Display_Name__c;

    for (Registration__c reg : registrations) {
      RosterRowWrapper rosterRow = new RosterRowWrapper();
      rosterRow.registrationId = reg.Id;
      rosterRow.studentId = reg.Registrant__r.Id;
      rosterRow.studentName = reg.Registrant__r.Name;
      rosterRow.pronouns = reg.Registrant__r.Pronouns__c;
      rosterRow.slackImage = reg.Registrant__r.Slack_Image__c;
      rosterRow.gitHub = reg.Registrant__r.Github_Username__c;

      if (!reg.Attendances__r.isEmpty()) {
        rosterRow.attendanceId = reg.Attendances__r[0].Id;
        rosterRow.present = reg.Attendances__r[0].Present__c ? 'true' : 'false';
        rosterRow.isAttendanceMarked = true;
      } else {
        rosterRow.isAttendanceMarked = false;
      }

      rosterRows.add(rosterRow);
    }
  }

  public class RosterRowWrapper {
    public Id attendanceId { get; set; }
    public Id registrationId { get; set; }
    public Id studentId { get; set; }
    public String slackImage { get; set; }
    public String studentName { get; set; }
    public String pronouns { get; set; }
    public String gitHub { get; set; }
    public String present { get; set; }
    public Boolean isAttendanceMarked { get; set; }
  }

  public void saveAttendances() {
    List<Attendance__c> attendances = new List<Attendance__c>();

    for (RosterRowWrapper rosterRow : rosterRows) {
      attendances.add(
        createAttendance(
          rosterRow.attendanceId,
          rosterRow.registrationId,
          rosterRow.studentId,
          Boolean.valueOf(rosterRow.present)
        )
      );
    }
    upsert attendances;
    getRegistrations();
  }

  // Notes
  public PageReference saveNotes() {
    if (String.isBlank(notes)) {
      return null;
    }
    studentEngagement = new Student_Engagement__c(
      Engagement_Type__c = notesType,
      Student__c = studentId,
      Engagement_Notes__c = notes,
      WFT_Staff_Member__c = currentUserContactId
    );

    insert studentEngagement;

    closeNotes();
    return null;
  }

  private void clearNotesValues() {
    studentId = null;
    studentName = null;
    notesType = null;
    notes = null;
  }

  public void closeNotes() {
    displayNotes = false;
    clearNotesValues();
  }

  public void showNotes() {
    displayNotes = true;
  }

  //Gets info of user who is submitting Attendnace or Notes
  public void getUserContactId() {
    String userId = UserInfo.getUserId();
    User currentUser = [SELECT Id, contactId FROM User WHERE Id = :userId];

    if (String.isBlank(currentUser.contactId)) {
      List<Contact> userContacts = [
        SELECT Id
        FROM Contact
        WHERE User__c = :userId
      ];
      if (userContacts.size() > 0) {
        currentUserContactId = userContacts[0].Id;
      }
    }
  }
}