force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>Created by BN
For: Geekwise User
Function: Track student attendance in classes. Could be used for events later.
Populated by: User either manually or through Instructor Portal.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <description>Created By: RS
Business Unit: Look-up
Purpose: To Track</description>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Class_Capacity__c</fullName>
    <defaultValue>27</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display max students allowed to register for the class
Populate: Default value, manual adjustment</description>
    <label>Class Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Cost__c.field-meta.xml
<CustomField>
    <fullName>Class_Cost__c</fullName>
    <defaultValue>250.00</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the cost of the class
Populated: Default value, manual adjustment</description>
    <label>Class Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Description__c.field-meta.xml
<CustomField>
    <fullName>Class_Description__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Details what will be taught in the class
Populated: Auto via Process, manual if Class is &quot;Other&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If this class is of type &quot;Other&quot;, please fill out this field with a description of the course.</inlineHelpText>
    <label>Class Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Class_Skill_Level__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the skill level of the current class
Populated: Auto via Web form/Process</description>
    <label>Class Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Instruction_Time__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Time__c</fullName>
    <label>Instruction Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>36 hrs. Instruction</fullName>
                <default>true</default>
                <label>36 hrs. Instruction</label>
            </value>
            <value>
                <fullName>18 hrs. Instruction</fullName>
            </value>
            <value>
                <fullName>84 hrs. Instruction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Posted_to_Website__c.field-meta.xml
<CustomField>
    <fullName>Posted_to_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will appear on the website.</inlineHelpText>
    <label>Posted to Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Removed_from_Website__c.field-meta.xml
<CustomField>
    <fullName>Removed_from_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will be removed from the website.</inlineHelpText>
    <label>Removed from Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Links the Registration record to a Contact
Populated: Manual/Auto with Web form</description>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Class Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WFTAttendanceTableTests.cls
@isTest
public class WFTAttendanceTableTests {
  @TestSetup
  static void setup() {
    Class__c classNoAttendance = new Class__c(
      Name = 'Test Class No Attendance',
      Class__c = 'JavaScript for Beginners',
      Class_Nights__c = 'Tuesday / Thursday',
      Start_Date__c = Date.today().addDays(30),
      End_Date__c = Date.today().addDays(60),
      Instruction_Time__c = '36 hrs. Instruction',
      Class_Capacity__c = 35,
      Class_Skill_Level__c = 'Beginner',
      Class_Cost__c = 250,
      Class_Description__c = 'This is a test class.',
      Posted_To_Website__c = Date.today(),
      Removed_From_Website__c = Date.today().addDays(30)
    );
    insert classNoAttendance;

    Class__c classRec = new Class__c(
      Name = 'Test Websites for Beginners',
      Class__c = 'Websites for Beginners',
      Class_Nights__c = 'Monday / Wednesday',
      Start_Date__c = Date.today().addDays(30),
      End_Date__c = Date.today().addDays(60),
      Instruction_Time__c = '36 hrs. Instruction',
      Class_Capacity__c = 35,
      Class_Skill_Level__c = 'Beginner',
      Class_Cost__c = 250,
      Class_Description__c = 'This is a test class.',
      Posted_To_Website__c = Date.today(),
      Removed_From_Website__c = Date.today().addDays(30)
    );
    insert classRec;

    Contact student = new contact(
      firstName = 'Student1',
      lastName = 'Student1',
      email = 'cohortdevorgs+bwadmin@gmail.com.invalid'
    );
    insert student;

    Contact student2 = new Contact(
      firstName = 'Student2',
      lastName = 'Student2',
      email = 'cohortdevorgs+bwadmin@gmail.com.invalid2'
    );
    insert student2;

    Contact student3 = new Contact(
      firstName = 'Student3',
      lastName = 'Student3',
      email = 'cohortdevorgs+bwadmin@gmail.com.invalid3'
    );
    insert student3;

    Registration__c registration = new registration__c(
      registrant__c = student.Id,
      Class__c = classRec.Id
    );
    insert registration;

    Registration__c registration2 = new registration__c(
      registrant__c = student2.Id,
      Class__c = classRec.Id
    );
    insert registration2;

    Registration__c registration3 = new registration__c(
      registrant__c = student3.Id,
      Class__c = classRec.Id
    );
    insert registration3;

    List<Attendance__c> attendance = new List<Attendance__c>();

    // start of student4
    Contact student4 = new Contact(
      firstName = 'Student4',
      lastName = 'Student4',
      email = 'cohortdevorgs+student4@gmail.com.invalid2'
    );
    insert student4;

    Registration__c registration4 = new registration__c(
      registrant__c = student4.Id,
      Class__c = classRec.Id
    );
    insert registration4;

    Attendance__c att4 = new Attendance__c(
      registration__c = registration4.Id,
      date__c = Date.valueOf('2021-01-04'),
      present__c = false,
      student__c = student4.Id
    );

    attendance.add(att4);
    // end of student4

    Attendance__c newAttendance = new Attendance__c(
      registration__c = registration.Id,
      date__c = Date.valueOf('2021-02-04'),
      present__c = true,
      student__c = student.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration.Id,
      date__c = Date.valueOf('2021-02-24'),
      present__c = true,
      student__c = student.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration2.Id,
      date__c = Date.valueOf('2021-01-19'),
      present__c = true,
      student__c = student2.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration2.Id,
      date__c = Date.valueOf('2021-01-21'),
      present__c = true,
      student__c = student2.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration2.Id,
      date__c = Date.valueOf('2021-01-26'),
      present__c = false,
      student__c = student2.Id
    );
    attendance.add(newAttendance);

    //Student 3
    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-01-19'),
      present__c = false,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-01-21'),
      present__c = true,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-01-26'),
      present__c = false,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-01-28'),
      present__c = false,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-02-02'),
      present__c = true,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    newAttendance = new Attendance__c(
      registration__c = registration3.Id,
      date__c = Date.valueOf('2021-02-04'),
      present__c = true,
      student__c = student3.Id
    );
    attendance.add(newAttendance);

    insert attendance;
  }

  @isTest
  static void getAttendancesTest() {
    Map<String, List<String>> attMap = new Map<String, List<String>>();
    Class__c testClass = [
      SELECT Id
      FROM Class__c
      WHERE Class_Nights__c = 'Monday / Wednesday'
      LIMIT 1
    ];

    Test.startTest();
    attMap = WFTAttendanceTableController.getAttendances(testClass.Id);
    Test.stopTest();

    System.assertEquals(5, attMap.size());
  }

  @isTest
  static void getAttendancesTestNoAttendances() {
    Map<String, List<String>> attMap = new Map<String, List<String>>();
    Class__c testClass = [
      SELECT Id
      FROM Class__c
      WHERE Class__c = 'JavaScript for Beginners'
      LIMIT 1
    ];

    Test.startTest();
    attMap = WFTAttendanceTableController.getAttendances(testClass.Id);
    Test.stopTest();

    System.assertEquals(0, attMap.size());
  }
}