force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>Created by BN
For: Geekwise User
Function: Track student attendance in classes. Could be used for events later.
Populated by: User either manually or through Instructor Portal.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <description>Created By: RS
Business Unit: Look-up
Purpose: To Track</description>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Links the Registration record to a Contact
Populated: Manual/Auto with Web form</description>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Class Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/Student_Engagement__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Student Interactions, Volunteering, etc.</description>
    <label>Student Engagement</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Student Engagement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Engagement__c/fields/Engagement_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Notes__c</fullName>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy employees
Populated: Manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy students
Populated: Manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Engagements (Student)</relationshipLabel>
    <relationshipName>Student_Engagements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WFTClassRosterTests.cls
@isTest
public with sharing class WFTClassRosterTests {
  @TestSetup
  static void makeData(){
    User adminUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator'  
              AND UserRole.Name = 'System Administrator' AND IsActive = true LIMIT 1];
      
    System.runAs ( adminUser ) {
      Contact currUserAsContact = new Contact(firstName = 'Contact', lastName = 'User111', email = 'currUserAsContact111@test.com', User__c = adminUser.Id);
      insert currUserAsContact;
    }
          
    Class__c newClass = new Class__c(
      Name = 'Websites for Beginners',
      Class_nights__c = 'Monday / Wednesday',
      Start_date__c = date.today(),
      End_date__c = date.today() + 45
    );
    insert newClass;

    //student 1
    contact student1 = new contact(
      firstName = 'Student1',
      lastName = 'Student1',
      wft_student__c = true,
      email = 'student1@gmail.com'
    );
    insert student1;

    registration__c registration1 = new registration__c(
      registrant__c = student1.Id,
      class__c = newClass.Id
    );
    insert registration1;

    Attendance__c attendance1 = new Attendance__c(
        registration__c = registration1.Id,
        date__c = date.today(),
        present__c = false,
        student__c = student1.Id
      );
    insert attendance1;

    //student 2
    contact student2 = new contact(
        firstName = 'Student2',
        lastName = 'Student2',
        wft_student__c = true,
        email = 'student2@gmail.com'
      );
    insert student2;

    registration__c registration2 = new registration__c(
        registrant__c = student2.Id,
        class__c = newClass.Id
      );
    insert registration2;

    Attendance__c attendance2 = new Attendance__c(
        registration__c = registration2.Id,
        date__c = date.today(),
        present__c = true,
        student__c = student2.Id
      );
    insert attendance2;

    //student 3
    contact student3 = new contact(
      firstName = 'Student3',
      lastName = 'Student3',
      wft_student__c = true,
      email = 'student3@gmail.com'
    );
    insert student3;

    registration__c registration3 = new registration__c(
      registrant__c = student3.Id,
      class__c = newClass.Id
    );
    insert registration3;

    Attendance__c attendance3 = new Attendance__c(
      registration__c = registration3.Id,
      date__c = date.today(),
      present__c = false,
      student__c = student3.Id
    );
    insert attendance3;
  }


  @isTest
  static void getRegistrationsTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    c.classId = [SELECT Id FROM Class__c LIMIT 1].id;
    c.selectedDate = date.today();
    
    Test.startTest();
    c.getRegistrations();
    Test.stopTest();

    System.assertEquals(3, c.rosterRows.size());
  }

  @isTest
  static void getRegistrationsWithNoSelectedDateTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    c.classId = [SELECT Id FROM Class__c LIMIT 1].id;
    c.selectedDate = null;
    
    Test.startTest();
    c.getRegistrations();
    Test.stopTest();

    System.assertEquals(0, c.rosterRows.size());
}

  @isTest
  static void getRegistrationsWithNoAttendanceTest() {
    WFTClassRosterController c = new WFTClassRosterController();

    Class__c class5 = new Class__c(
      Name = 'Websites for Beginners Class 5',
      Class_nights__c = 'Monday / Wednesday',
      Start_date__c = date.today(),
      End_date__c = date.today() + 45
    );
    insert class5;

    contact student5 = new contact(
      firstName = 'Student5',
      lastName = 'Student5',
      wft_student__c = true,
      email = 'student5@gmail.com'
    );
    insert student5;

    registration__c registration5 = new registration__c(
      registrant__c = student5.Id,
      class__c = class5.Id
    );
    insert registration5;

    c.classId = class5.Id;
    c.selectedDate = date.today();
    
    Test.startTest();
    c.getRegistrations();
    Test.stopTest();

    System.assertEquals(1, c.rosterRows.size());
  }
 
  @isTest 
  static void  saveAttendancesTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    c.classId = [SELECT Id FROM Class__c LIMIT 1].id;
    c.selectedDate = date.today();
    c.getRegistrations();
    
    Test.startTest();
    c.saveAttendances();
    Test.stopTest();

    System.assertEquals(3, c.rosterRows.size());
  }

  @isTest 
  static void saveNotesTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    c.notes = 'Test notes';

    Test.startTest();
    c.saveNotes();
    Test.stopTest();

    Student_Engagement__c notes = [SELECT Engagement_Notes__c FROM Student_Engagement__c LIMIT 1];
    System.assertEquals('Test notes', notes.Engagement_Notes__c);
  }

  @isTest 
  static void saveNotesBlankTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    c.notes = '';

    Test.startTest();
    c.saveNotes();
    Test.stopTest();

    list<Student_Engagement__c> notes = [SELECT Engagement_Notes__c FROM Student_Engagement__c];
    System.assertEquals(0, notes.size());
  }

  @isTest 
  static void createAttendanceTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    Registration__c reg = [SELECT Id, Registrant__c FROM Registration__c LIMIT 1];
    
    Test.startTest();
    Attendance__c att = c.createAttendance(null, reg.Id, reg.registrant__c, true);
    Test.stopTest();
    
    System.assertEquals(true, att.present__c);
  }

  @isTest 
  static void showNotesTest() {
    WFTClassRosterController c = new WFTClassRosterController();
    
    Test.startTest();
    c.showNotes();
    Test.stopTest();

    System.assertEquals(true, c.displayNotes);
  }

  @isTest 
  static void getUserContactIdTest() {
    WFTClassRosterController c = new WFTClassRosterController();

    contact contactUser = new contact(
      firstName = 'Contact1',
      lastName = 'User1',
      email = 'contactUser11@gmail.com',
      user__c = UserInfo.getUserId()
    );
    insert contactUser;

    Test.startTest();
    c.getUserContactId();
    Test.stopTest();

    system.assertEquals(contactUser.Id, c.currentUserContactId);
  }
}