force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <description>Created by BN
For: Geekwise User
Function: Track student attendance in classes. Could be used for events later.
Populated by: User either manually or through Instructor Portal.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Present__c.field-meta.xml
<CustomField>
    <fullName>Present__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <description>Created By: RS
Business Unit: Look-up
Purpose: To Track</description>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By BN
For GW Users
Track student attendance
Populated manually</description>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendances</relationshipLabel>
    <relationshipName>Attendance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WFTAttendanceTableController.cls
public with sharing class WFTAttendanceTableController {
  @AuraEnabled(cacheable=true)
  public static Map<String, List<String>> getAttendances(Id recordId) {
    List<Date> attendanceDates = new List<Date>();
    List<String> attendanceNames = new List<String>();
    List<String> datesForHeader = new List<String>();
    Map<String, List<String>> attendanceMap = new Map<String, List<String>>();

    List<Attendance__c> attendanceRecords = new List<Attendance__c>();
    Integer maxNumbOfAttendanceDates;

    attendanceRecords = [
      SELECT id, Student__r.name, Date__c, Present__c
      FROM Attendance__c
      WHERE Registration__r.Class__r.id = :recordId
      ORDER BY Student__r.name, Date__c
    ];

    if (attendanceRecords.isempty()) {
      return attendanceMap;
    }

    //loops through attendance records for student names & attendance dates.
    for (Attendance__c Student : attendanceRecords) {
      if (!attendanceNames.contains((Student.Student__r.name))) {
        attendanceNames.add(Student.Student__r.name);
      }
      if (
        Student.Date__c != null && !attendanceDates.contains((Student.Date__c))
      ) {
        attendanceDates.add(Student.Date__c);
      }
    }

    attendanceNames.sort();
    attendanceDates.sort();
    maxNumbOfAttendanceDates = attendanceDates.size();

    // Add header row with dates
    for (Datetime dt : attendanceDates) {
      datesForHeader.add(dt.format('MM/dd/yy', 'PDT'));
    }

    attendanceMap.put('Student', datesForHeader);

    //loops through attendance records for class datepubl
    for (String sName : attendanceNames) {
      List<String> aDisplay = new List<String>();
      for (Date d : attendanceDates) {
        if (attendanceRecords.isEmpty()) {
          aDisplay.add('N/A');
        } else {
          Attendance__c a = attendanceRecords.remove(0);

          if (sName == a.Student__r.Name) {
            if (d != a.Date__c) {
              aDisplay.add('N/A');

              if (attendanceRecords.isEmpty())
                attendanceRecords.add(a);
              else
                attendanceRecords.add(0, a);
            } else {
              aDisplay.add(a.Present__c ? 'P' : 'A');
            }
          } else {
            List<Attendance__c> copy = new List<Attendance__c>();
            copy.add(a);
            copy.addAll(attendanceRecords);
            attendanceRecords = copy;
            break;
          }
        }
      }

      Integer numbMissingAttendance =
        maxNumbOfAttendanceDates - aDisplay.size();
      for (Integer i = 0; i < numbMissingAttendance; i++) {
        aDisplay.add('N/A');
      }

      attendanceMap.put(sName, aDisplay);
    }

    return attendanceMap;
  }
}