force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Relates a Contact record as an Instructor for this class
Populated: Manual</description>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Qualified_Instructor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Instructor)</relationshipLabel>
    <relationshipName>Classes_Instructed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gateway__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cowork</fullName>
            </value>
            <value>
                <fullName>WFT</fullName>
            </value>
            <value>
                <fullName>Shift3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SandboxInitializationWithData.cls
public class SandboxInitializationWithData implements SandboxPostCopy{
    //The number of each type of Object to create when Class Runs
    public Integer numOfAccounts = 10, numOfContactsPerAccount = 5, numOfOpps = 20,
    numOfCasesIT = 5, numOfCasesSFDC = 5, numOfRegistrationsPerClass = 5, numOfClasses = 8;

    public void runApexClass(SandboxContext context) {
        System.debug('Org ID: ' + context.organizationId());
        System.debug('Sandbox ID: ' + context.sandboxId());
        System.debug('Sandbox Name: ' + context.sandboxName());

        Id individualAcctRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId();

        List<Account> existingAccts = [SELECT Id FROM Account WHERE RecordTypeId = :individualAcctRtId];

        if (existingAccts.size() == 0) {
            Account acct = new Account(
                Name = 'Individuals',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId()
            );

            insert acct;
        }
     
        Gateway__c coworkGateway = new Gateway__c(
            Name = 'Cowork (Test)',
            Department__c = 'Cowork',
            Active__c = true
        );

        
        Gateway__c wftGateway = new Gateway__c(
            Name = 'WFT (Test)',
            Department__c = 'WFT',
            Active__c = true
        );

        insert new List<Gateway__c>{coworkGateway, wftGateway};

        //Create accounts
        List<Account> accounts = TestDataFactory.createMultipleAccounts(numOfAccounts, '');
        insert accounts;

        //Add contacts for each account
        List<Contact> contacts = new List<Contact>();
        for(Account acc : accounts) {
            contacts.addAll(TestDataFactory.createMultipleContacts(numOfContactsPerAccount, acc));
        }
        insert contacts;
        
        //Create Opps
        TestDataFactory.createMultipleOpportunities(numOfOpps, '');

        // Create cases
        Account bwAccount = TestDataFactory.createAccount();
        bwAccount.Name = 'Bitwise Industries';
        insert bwAccount;
        TestDataFactory.createMultipleCases(numOfCasesIT, 'IT', bwAccount);
        TestDataFactory.createMultipleCases(numOfCasesSFDC, 'SFDC', bwAccount);
        
        //Create first set of instructors - InPerson
        List<Contact> instructorsInPerson = TestDataFactory.createMultipleContacts(numOfClasses, bwAccount);
        for(Contact c : instructorsInPerson ) {
            c.Qualified_Instructor__c = true;
        }
        insert instructorsInPerson;

        // Create first round of classes - Attendance type:In-Person and Market:Fresno
        List<Class__c> classesInPerson = TestDataFactory.createClassRound('In-Person','Fresno');
        //add instructor for each class & save
        for (Class__c cls : classesInPerson) {
            cls.Instructor__c = instructorsInPerson.remove(0).Id;
        }
        insert classesInPerson;
        
        //Add Registrations to first round of classes
        for (Class__c cls : classesInPerson) {
            TestDataFactory.addRegistrationsToClass(numOfRegistrationsPerClass, cls);
        }

        //Create second set of instructors - Virtual
        List<Contact> instructorsVirtual = TestDataFactory.createMultipleContacts(numOfClasses, bwAccount);
        for(Contact c : instructorsVirtual ) {
            c.Qualified_Instructor__c = true;
        }
        insert instructorsVirtual;

        // Create second round of classes - Attendance type:Virtual and Market:Virtual
        List<Class__c> classesVirtual = TestDataFactory.createClassRound('Virtual','Virtual');
        //add instructor for each class & save
        for (Class__c cls : classesVirtual) {
            cls.Instructor__c = instructorsVirtual.remove(0).Id;
        }
        insert classesVirtual;
        
        //Add Registrations to Second round of classes
        for (Class__c cls : classesVirtual) {
            TestDataFactory.addRegistrationsToClass(numOfRegistrationsPerClass, cls);
        }

    }    
}