force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SandboxInitializationWithDataTest.cls
@isTest
public class SandboxInitializationWithDataTest {
    @isTest 
    public static void TestSandboxInitWithData(){
        SandboxInitializationWithData sbiData = new SandboxInitializationWithData();
        
        Test.startTest();
        Test.testSandboxPostCopyScript(sbiData, UserInfo.getOrganizationId(), UserInfo.getOrganizationId(), UserInfo.getOrganizationName());
        Test.stopTest();

        Integer totalContacts = (sbiData.numOfAccounts * sbiData.numOfContactsPerAccount) + sbiData.numOfOpps + sbiData.numOfCasesIT 
                    + sbiData.numOfCasesSFDC + sbiData.numOfClasses + sbiData.numOfClasses 
                    + (sbiData.numOfRegistrationsPerClass * sbiData.numOfClasses);

        Integer numOfAccountsDB = [SELECT Id FROM Account].size();
        //Number of Accounts + Number of Accounts made for Opps + 1 Individual Account + 1 Account for Cases
        System.assertEquals(sbiData.numOfAccounts + sbiData.numOfOpps + 2, numOfAccountsDB);

        Integer numOfContactsDB = [SELECT Id FROM Contact].size();
        System.assertEquals(totalContacts, numOfContactsDB);

        Integer numOfOppsDB = [SELECT Id FROM Opportunity].size();
        System.assertEquals(sbiData.numOfOpps, numOfOppsDB);

        Integer numOfCasesDB = [SELECT Id FROM Case].size();
        System.assertEquals((sbiData.numOfCasesIT + sbiData.numOfCasesSFDC), numOfCasesDB);

        Integer numOfClassesDB = [SELECT Id FROM Class__c].size();
        System.assertEquals(sbiData.numOfClasses, numOfClassesDB);

        Integer numOfRegistrationsDB = [SELECT Id FROM Registration__c].size();
        System.assertEquals((sbiData.numOfRegistrationsPerClass * sbiData.numOfClasses), numOfRegistrationsDB);

    }
}