force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Class_Capacity__c</fullName>
    <defaultValue>27</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display max students allowed to register for the class
Populate: Default value, manual adjustment</description>
    <label>Class Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Cost__c.field-meta.xml
<CustomField>
    <fullName>Class_Cost__c</fullName>
    <defaultValue>250.00</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the cost of the class
Populated: Default value, manual adjustment</description>
    <label>Class Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Description__c.field-meta.xml
<CustomField>
    <fullName>Class_Description__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Details what will be taught in the class
Populated: Auto via Process, manual if Class is &quot;Other&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If this class is of type &quot;Other&quot;, please fill out this field with a description of the course.</inlineHelpText>
    <label>Class Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Class_Skill_Level__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the skill level of the current class
Populated: Auto via Web form/Process</description>
    <label>Class Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BW_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Posted_to_Website__c.field-meta.xml
<CustomField>
    <fullName>Posted_to_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will appear on the website.</inlineHelpText>
    <label>Posted to Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Removed_from_Website__c.field-meta.xml
<CustomField>
    <fullName>Removed_from_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will be removed from the website.</inlineHelpText>
    <label>Removed from Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Section_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Created By: CC
Purpose: Number in order to identify the different sections of a class in a round.</description>
    <inlineHelpText>Starting at 1 the Section number will increase for each identical class created.</inlineHelpText>
    <label>Section Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>RS</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Zoom_Meeting_ID__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zoom Meeting ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Contains information on markets including description and postal codes.</description>
    <label>Market</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>TL</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/WFT_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WFT Custom Settings</label>
</CustomObject>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Enable_Class_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Enable_Class_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: CC
Purpose: Enable Class trigger.</description>
    <inlineHelpText>Enable/Disable Class Trigger.</inlineHelpText>
    <label>Enable Class Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_API_JWT__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_JWT__c</fullName>
    <description>Created By: CC
Purpose: JWT Authentication Token.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>JWT Authentication Token</inlineHelpText>
    <label>Zoom API JWT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_API_User__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_User__c</fullName>
    <description>Created By: CC
Purpose: Email or UserId of the Zoom API user who will be scheduling meetings.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email or UserId of the Zoom API user who will be scheduling meetings.</inlineHelpText>
    <label>Zoom API User</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_Meeting_Host__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_Host__c</fullName>
    <description>Created By: CC
Purpose: Store Email or Zoom Id of user who be the default host for WFT Zoom Meetings.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Store Email or Zoom Id of user who be the default host for WFT Zoom Meetings. Only one user can be host.</inlineHelpText>
    <label>Zoom Meeting Host</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ZoomServiceTests.cls
@isTest
public  class ZoomServiceTests {
    @testSetup
    public static void setup() {
        WFT_Custom_Settings__c customSetting = new WFT_Custom_Settings__c();
        customSetting.Zoom_Meeting_Host__c = 'ccoelho@bitwiseindustries.com';
        customSetting.Zoom_API_JWT__c = 'testKey';
        customSetting.Zoom_API_User__c = 'WFTIntegrations@bitwiseindustries.com';
        customSetting.Enable_Class_Trigger__c = true;
        insert customSetting;
    }
    @IsTest
    public static void createZoomMeetingObjectETTest() {
       Class__c classET = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Toledo',
            Time_Zone__c = 'Eastern',
            Section_Number__c = 1,
            Class_Nights__c = 'Monday / Wednesday',
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        String expectedTimeZone = 'America/New_York';
        Test.startTest();
        ZoomService.ZoomMeeting testZoomMeeting = ZoomService.createZoomMeetingObject(classET);
        System.AssertEquals(expectedTimeZone,testZoomMeeting.timezone);
        Test.stopTest();
        
    }
    @isTest
     public static void createZoomMeetingObjectCTTest() {
       Class__c classCT = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Toledo',
            Time_Zone__c = 'Central',
            Section_Number__c = 1,
            Class_Nights__c = 'Tuesday / Thursday',
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        String expectedTimeZone = 'America/Chicago';
        Test.startTest();
        ZoomService.ZoomMeeting testZoomMeeting = ZoomService.createZoomMeetingObject(classCT);
        System.AssertEquals(expectedTimeZone,testZoomMeeting.timezone);
        Test.stopTest();
        
    }
    @isTest
     public static void createZoomMeetingObjectMTTest() {
       Class__c classMT = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Toledo',
            Time_Zone__c = 'Mountain',
            Section_Number__c = 1,
            Class_Nights__c = 'Wednesday',
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        String expectedTimeZone = 'America/Denver';
        Test.startTest();
        ZoomService.ZoomMeeting testZoomMeeting = ZoomService.createZoomMeetingObject(classMT);
        System.AssertEquals(expectedTimeZone,testZoomMeeting.timezone);
        Test.stopTest();
        
    }
    @isTest
     public static void createZoomMeetingObjectPTTest() {
       Class__c classPT = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Fresno',
            Time_Zone__c = 'Pacific',
            Section_Number__c = 1,
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        String expectedTimeZone = 'America/Los_Angeles';
        Test.startTest();
        ZoomService.ZoomMeeting testZoomMeeting = ZoomService.createZoomMeetingObject(classPT);
        System.AssertEquals(expectedTimeZone,testZoomMeeting.timezone);
        Test.stopTest();      
    }
    @isTest
    public static void createMeetingTest() {
        Class__c classPT = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Fresno',
            Time_Zone__c = 'Pacific',
            Section_Number__c = 1,
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        List<Class__c> classes = new List<Class__c>();
        List<Class__c> returnedClasses = new List<Class__c>();
        classes.add(classPT);
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('ZoomResponseMock');
        mock.setStatusCode(201);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);
         
        Test.startTest();
        returnedClasses = ZoomService.createMeeting(classes);
        System.assertEquals('1100000', returnedClasses[0].Zoom_Meeting_Id__c);
        Test.stopTest();
    }

    public static void createMeetingTestFailedResponse() {
        Class__c classPT = new Class__c(
            Name = 'Test Websites for Beginners',
            Class__c = 'Websites for Beginners',
            Market__c = 'Fresno',
            Time_Zone__c = 'Pacific',
            Section_Number__c = 1,
            Start_Date__c = Date.today().addDays(30),
            End_Date__c = Date.today().addDays(60),  
            Class_Capacity__c = 35,
            Class_Skill_Level__c = 'Beginner',
            Class_Cost__c = 250,
            Class_Description__c = 'This is a test class.',
            Posted_To_Website__c = Date.today(),
            Removed_From_Website__c = Date.today().addDays(30)
        );

        List<Class__c> classes = new List<Class__c>();
        List<Class__c> returnedClasses = new List<Class__c>();
        classes.add(classPT);
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('ZoomResponseMock');
        mock.setStatusCode(400);
        mock.setHeader('Content-Type', 'application/json');
        
        Test.setMock(HttpCalloutMock.class, mock);
         
        Test.startTest();
        returnedClasses = ZoomService.createMeeting(classes);
        System.assertEquals(classes[0].Zoom_Meeting_Id__c, returnedClasses[0].Zoom_Meeting_Id__c);
        Test.stopTest();
    }

}