force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Co_Teacher__c.field-meta.xml
<CustomField>
    <fullName>Co_Teacher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Relates a Contact record as a Co=Teacher for the Class
Populated: Manual</description>
    <label>Co-Teacher</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Co-Teacher)</relationshipLabel>
    <relationshipName>Classes_CoTaught</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Relates a Contact record as an Instructor for this class
Populated: Manual</description>
    <label>Instructor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Qualified_Instructor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Classes (Instructor)</relationshipLabel>
    <relationshipName>Classes_Instructed</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Links the Registration record to a Contact
Populated: Manual/Auto with Web form</description>
    <label>Registrant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Class Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WFTPortalHomeTests.cls
@isTest
public class WFTPortalHomeTests {
    
    @testSetup
    static void setup() {
        Account a = new Account(Name='Test Account');
        insert a;
        Contact teacher = new Contact(FirstName = 'Teacher', LastName = 'Teaher', AccountId = a.Id, Email = 'teacher@teacher.com', Qualified_Instructor__c = true);
        insert teacher;

        Contact coTeacher = new Contact(FirstName = 'co-teacher', LastName = 'co-teacher', AccountId = a.Id, Email = 'co-teacher@co-teacher.com', Qualified_Instructor__c = true);
        insert coTeacher;
        
        Contact student = new Contact(FirstName = 'student', LastName = 'student', AccountId = a.Id, Email = 'student@bw.com');
        insert student;
    
        class__c newClass = new class__c(name = 'Test Class', Instructor__c = teacher.Id, Co_Teacher__c = coTeacher.Id,
        class_nights__c = 'Monday / Wednesday', start_date__c = date.today() - 10, end_date__c = date.today() + 45);
        insert newClass;
        
        insert new Registration__c(Registrant__c = student.Id, Class__c = newClass.Id);

        class__c newClass2 = new class__c(name = 'Test Class', Instructor__c = coTeacher.Id,
        class_nights__c = 'Monday / Wednesday', start_date__c = date.today() - 10, end_date__c = date.today() + 45);
        insert newClass2;
        
        insert new Registration__c(Registrant__c = student.Id, Class__c = newClass2.Id);
    }
    
    
    static testMethod void testGetClassesWFTProfile() {    
	
        UserRole ur = [SELECT Id, Name, PortalType, PortalAccountId FROM UserRole where Name = 'System Administrator' LIMIT 1];
		User adminUser = [SELECT Id, Name, UserRoleId FROM User Where Profile.Name='System Administrator' AND IsActive = true LIMIT 1];
        System.debug(ur);
		adminUser.UserRoleId = ur.Id;
        update adminUser;
        System.debug(adminUser);

        User teacherUser;
        System.runAs ( adminUser ) {
            
			Contact teacher = [SELECT Id FROM Contact WHERE Email='teacher@teacher.com'];
            Profile p = [SELECT Id FROM Profile WHERE Name='WFT Community User'];

            teacherUser = new User(Alias = 'newUser', Email='teacher@teacher.com',
            EmailEncodingKey='UTF-8', FirstName='Testing', LastName='Testing', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, ContactId = teacher.Id, IsActive = true,
            TimeZoneSidKey='America/Los_Angeles', UserName='teacher@teacher.com');

            insert teacherUser;
        }
 
        System.runAs(teacherUser) {
            WFTPortalHomeController pc = new  WFTPortalHomeController();  
            pc.getClasses();
            System.assertEquals(1, pc.classes.size());
        }
    }

    static testMethod void testGetClassesAdminProfile() {    
	
        WFTPortalHomeController pc = new  WFTPortalHomeController();  
        pc.getClasses();
        System.assertEquals(2, pc.classes.size());

    }

    static testMethod void testGetClassesStandardUserProfile() {    
	
        UserRole ur = [SELECT Id, Name, PortalType, PortalAccountId FROM UserRole where Name = 'System Administrator' LIMIT 1];
		User adminUser = [SELECT Id, Name, UserRoleId FROM User Where Profile.Name='System Administrator' AND IsActive = true LIMIT 1];
        System.debug(ur);
		adminUser.UserRoleId = ur.Id;
        update adminUser;
        System.debug(adminUser);

        User teacherUser;
        System.runAs ( adminUser ) {
 
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

            teacherUser = new User(Alias = 'newUser2', Email='teacher@teacher.com',
            EmailEncodingKey='UTF-8', FirstName='Testing2', LastName='Testing2', LanguageLocaleKey='en_US',
            LocaleSidKey='en_US', ProfileId = p.Id, IsActive = true,
            TimeZoneSidKey='America/Los_Angeles', UserName='teacher2@teacher.com');

            insert teacherUser;
        }
 
        System.runAs(teacherUser) {
            WFTPortalHomeController pc = new  WFTPortalHomeController();  
            pc.getClasses();
            System.assertEquals(1, pc.classes.size());
        }
    }
    @isTest
    public static void testToClassRoster() {
        WFTPortalHomeController pc = new  WFTPortalHomeController();
		pc.recordId = 'classId';
		String url = pc.toClassRoster().getUrl();
		System.assertEquals(true, url.contains('classId'));
	}

    @isTest
	public static void testToApprenticeshipRoster() {
		WFTPortalHomeController pc = new  WFTPortalHomeController();
		pc.recordId = 'apprenticeshipId';
		String url = pc.toApprenticeshipRoster().getUrl();
		System.assertEquals(true, url.contains('apprenticeshipId'));
	}
}