force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Attendance_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Type__c</fullName>
    <label>Attendance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Cost__c.field-meta.xml
<CustomField>
    <fullName>Class_Cost__c</fullName>
    <defaultValue>250.00</defaultValue>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the cost of the class
Populated: Default value, manual adjustment</description>
    <label>Class Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Dont_Allow_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Dont_Allow_Registrations__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When this box is checked, students will no longer be able to register for this class on the website. Registrations may still be added manually by a Geekwise Staff Member or System Administrator.</inlineHelpText>
    <label>Don&apos;t Allow Registrations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Dont_Display_on_Website__c.field-meta.xml
<CustomField>
    <fullName>Dont_Display_on_Website__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To prevent certain courses from showing up on the website
Populated: Manually</description>
    <label>Don&apos;t Display on Website</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BW_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Posted_to_Website__c.field-meta.xml
<CustomField>
    <fullName>Posted_to_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will appear on the website.</inlineHelpText>
    <label>Posted to Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Removed_from_Website__c.field-meta.xml
<CustomField>
    <fullName>Removed_from_Website__c</fullName>
    <description>Created By: DA Business Unit: Geekwise Users Purpose: To Track when Geekwise Classes are posted on the website.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the class will be removed from the website.</inlineHelpText>
    <label>Removed from Website</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: AF; Business Unit: Geekwise Users; Purpose: Updates Class Status based on Start and End date; Populated: Auto via Formula</description>
    <formula>IF( Start_Date__c &gt; TODAY(), &apos;Upcoming&apos;, 
IF( End_Date__c &lt; TODAY(), &apos;Past&apos;, &apos;Active&apos; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>RS</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gateway__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cowork</fullName>
            </value>
            <value>
                <fullName>WFT</fullName>
            </value>
            <value>
                <fullName>Shift3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gateway__c/fields/Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Publishable_Key__c</fullName>
    <label>Publishable Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Contains information on markets including description and postal codes.</description>
    <label>Market</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/PostalCodes__c.field-meta.xml
<CustomField>
    <fullName>PostalCodes__c</fullName>
    <description>Created By: CC 
Department: 
BW Purpose: List of postal codes associated with a market.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Codes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Public_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Public_Knowledge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: CC
Purpose: Signify if a Market is public knowledge or not.</description>
    <inlineHelpText>Can the public know this Bitwise market exists?</inlineHelpText>
    <label>Public Knowledge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Track the status of the market.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>TL</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/WFTClassRegistrationTests.cls
@isTest
public class WFTClassRegistrationTests {
    private static Class__c clss;


    private static void setup() {
        StripePaymentServiceMock m = new StripePaymentServiceMock();
        StripePaymentService.Instance = m;

      	Market__c market = new Market__c(Name = 'Fresno',
								Public_Knowledge__c = true,
                                Time_Zone__c = 'Pacific',
								Status__c = 'Active', 
								PostalCodes__c = '93721,93725');
		insert market;
        
        clss = new Class__c(
			Name = 'Websites For Beginners',
            Class__c = 'Websites For Beginners',
            Start_Date__c = System.today() + 7,
            Posted_To_Website__c = System.today(),
            Removed_from_Website__c = System.today() + 1,
            Dont_Display_On_Website__c = false, 
            Dont_Allow_Registrations__c = false,
            Class_Cost__c = 10,
            Market__c = 'Fresno',
            Time_Zone__c = 'Pacific',
			Attendance_Type__c = 'Virtual'
        );

        insert clss;
         
    }


    @isTest
    private static void testSetup() {
        Test.startTest();
        setup();
        Test.stopTest();  
    }


    @isTest
    private static void testGPCWithoutContact() {
        setup();

        Id RecordTypeIdContact = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId();
        Account acct = new Account(
            Name = 'Spinach Corp',
            RecordTypeId = RecordTypeIdContact
        );
        insert acct;

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Bill';
        controller.paymentLastName = 'Nye';
        controller.paymentEmail = 'the@science.guy';
        controller.paymentPhone = '3141592653';
        controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact cont = [SELECT Id, Name, AccountId FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(cont.Name,'Bill Nye');
    }


    @isTest
    private static void testGPCWithContact() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, AccountId FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Name, cont.FirstName + ' ' + cont.LastName);

    }


    @isTest
    private static void testGetApiKey() {
        insert new Gateway__c(
            Publishable_Key__c = 'FOLLOW YOUR DREAMS',
            Department__c = 'WFT',
            Active__c = true
        );

        WFTClassRegistrationController controller = new WFTClassRegistrationController();

        Test.startTest();
        String apiKey = controller.getApiKey();
        Test.stopTest();   

        System.assertEquals(apiKey, 'FOLLOW YOUR DREAMS');
    }

   
    @isTest
    private static void testgetClassInfoById() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.getClassInfoById(clss.Id);
        System.assertEquals('Fresno', controller.currentClass.Market__c);
    }
	@isTest
    private static void testgetClassInfoByIdBadId() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
		delete clss;
        controller.getClassInfoById(clss.Id);
        System.assertEquals(null, controller.currentClass);
    }
	@isTest
	private static void testGetClassInfo() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
	
        Map<String,String> params = new Map<String,String>{'Name' => clss.Name, 'Type' => clss.Attendance_Type__c, 'Market' => clss.Market__c, 'TimeZone' => clss.Time_Zone__c};
		
		controller.getClassInfo(params);
        
        System.assertEquals(clss.Id, controller.classId);
    }
	@isTest
	private static void testGetClassInfoMissingParam() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
	
        Map<String,String> params = new Map<String,String>{'Name' => clss.Name,  'Market' => clss.Market__c};
	
		controller.getClassInfo(params);
        
        System.assertEquals(null, controller.currentClass);
    }

	@isTest
	private static void testGetClassInfoBadParams() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
	
        Map<String,String> params = new Map<String,String>{'Name' => 'WFB', 'Type' => 'V', 'Market' => 'San Francisco'};
	
		controller.getClassInfo(params);
        
        System.assertEquals(null, controller.currentClass);
    }

	@isTest 
	private static void testProcessTokenNoClass() {
		setup();
		PageReference pageRef = Page.WFTClassRegistration;
		delete clss;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);
		WFTClassRegistrationController controller = new WFTClassRegistrationController();
		controller.paymentFirstName = 'Bill';
        controller.paymentLastName = 'Nye';
        controller.paymentEmail = 'the@science.guy';
        controller.paymentPhone = '3141592653';
		PageReference result = controller.processToken();
		System.assertEquals(null,result);
	}

    @isTest
    private static void testStudentSource1() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        controller.studentSource = 'Bus Wrap';

        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, Student_Source__c, Student_Source_Fill_In__c FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Student_Source__c, controller.studentSource);
    }
     @isTest
     private static void testStudentSource2() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        controller.studentSource = 'Bitwise Employee';
        controller.employeeFillIn = 'Test Dude';
        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, Student_Source__c, Student_Source_Fill_In__c FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Student_Source__c, controller.studentSource);
        System.assertEquals(testCont.Student_Source_Fill_In__c, controller.employeeFillIn);
     }
    
    @isTest
    private static void testStudentSource3() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        controller.studentSource = 'Advertisement';
        controller.adFillIn = 'Test Ad';
        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, Student_Source__c, Student_Source_Fill_In__c FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Student_Source__c, controller.studentSource);
        System.assertEquals(testCont.Student_Source_Fill_In__c, controller.adFillIn);
     }
    
    @isTest    
    private static void testStudentSource4() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        controller.studentSource = 'Other';
        controller.otherFillIn = 'Test Other';
        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, Student_Source__c, Student_Source_Fill_In__c FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Student_Source__c, controller.studentSource);
        System.assertEquals(testCont.Student_Source_Fill_In__c, controller.otherFillIn);

     }
    
    @isTest
    private static void testStudentSource5() {
        setup();

        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

        Account acct = new Account(
            Name = 'Spinach Corp'
        );
        insert acct;

        Contact cont = new Contact(
            FirstName = 'Popeye',
            LastName = 'The Sailor',
            Email = 'popeye@spinachcorp.com',
            AccountId = acct.Id
        );
        insert cont;

        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.paymentFirstName = 'Popeye';
        controller.paymentLastName = 'The Sailor';
        controller.paymentEmail = 'popeye@spinachcorp.com';
        controller.paymentPhone = '3141592653';
         controller.postalStreet = '700 Van Ness Ave';
        controller.postalCity = 'Fresno';
        controller.postalState = 'California';
        controller.postalCode = '93721';

        controller.studentSource = 'Social Media';
        controller.socialMediaValue = 'Facebook';
        Test.startTest();
        controller.processToken();
        Test.stopTest();   

        Contact testCont = [SELECT Id, Name, Student_Source__c, Student_Source_Fill_In__c FROM Contact WHERE Email LIKE :controller.paymentEmail LIMIT 1];
        System.assertEquals(testCont.Student_Source__c, controller.socialMediaValue);

     }

     @isTest
      private static void onPageLoadTest() {
		setup();
        PageReference pageRef = Page.WFTClassRegistration;
        pageRef.getParameters().put('id', clss.Id);
        Test.setCurrentPage(pageRef);

     	
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('MarComFacebookPixelMock');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

		WFTClassRegistrationController controller = new WFTClassRegistrationController();

        Test.startTest();
		controller.onPageLoad();
        Test.stopTest();
		System.assertEquals(200, controller.pixelStatusCode);

     }
     @isTest
     private static void testAllowedToRegister() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.currentClass = clss;
        System.assertEquals(true, controller.allowedToRegister('Fresno','93721'));   
     }

     @isTest
     private static void testAllowedToRegisterNotInMarket() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.currentClass = clss;
        System.assertEquals(false, controller.allowedToRegister('Bakersfield','00050'));   
     }
     @isTest
      private static void testAllowedToRegisterVirtualMarket() {
        setup();
        WFTClassRegistrationController controller = new WFTClassRegistrationController();
        controller.currentClass = clss;
        System.assertEquals(true, controller.allowedToRegister('Virtual','93721'));   
     }



}