force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Description__c.field-meta.xml
<CustomField>
    <fullName>Class_Description__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Details what will be taught in the class
Populated: Auto via Process, manual if Class is &quot;Other&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>If this class is of type &quot;Other&quot;, please fill out this field with a description of the course.</inlineHelpText>
    <label>Class Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Nights__c.field-meta.xml
<CustomField>
    <fullName>Class_Nights__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the nights a class will be held
Populated: Manual/Auto via Flow</description>
    <label>Class Nights</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WFT_Class_Nights</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <description>CC For Displaying a simplified name on the website</description>
    <formula>IF(ISPICKVAL(Class__c, &apos;Other&apos;), Other__c, TEXT(Class__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For Displaying a Simplified Name on the website</inlineHelpText>
    <label>Display Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the End Date of the current Class
Populated: Auto via Web form, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BW_Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Display the date a class starts
Populated: Auto via Flow Screen, manual adjustment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>RS</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Zoom_Link__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zoom Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Zoom_Meeting_ID__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zoom Meeting ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Contains information on markets including description and postal codes.</description>
    <label>Market</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>TL</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/WFT_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WFT Custom Settings</label>
</CustomObject>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Daily_User_Zoom_Meeting_API_Calls__c.field-meta.xml
<CustomField>
    <fullName>Daily_User_Zoom_Meeting_API_Calls__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Created By: CC
Purpose: Keep count of Zoom Meetings created in a day.
https://marketplace.zoom.us/docs/api-reference/rate-limits</description>
    <inlineHelpText>Count of Zoom Meetings CRED in a day. API Limit is 100 a day per hosting User.</inlineHelpText>
    <label>Daily User Zoom Meeting API Calls</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Most_Recent_Zoom_Meeting_API_Call__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Zoom_Meeting_API_Call__c</fullName>
    <description>Created By: CC
Purpose: Keeps date of most recent Meeting API call in a day. Date is based off UTC.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Keeps date of most recent Meeting API call in a day is based on UTC.</inlineHelpText>
    <label>Most Recent Zoom Meeting API Call</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_API_JWT__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_JWT__c</fullName>
    <description>Created By: CC
Purpose: JWT Authentication Token.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>JWT Authentication Token</inlineHelpText>
    <label>Zoom API JWT</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_API_User__c.field-meta.xml
<CustomField>
    <fullName>Zoom_API_User__c</fullName>
    <description>Created By: CC
Purpose: Email or UserId of the Zoom API user who will be scheduling meetings.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Email or UserId of the Zoom API user who will be scheduling meetings.</inlineHelpText>
    <label>Zoom API User</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_Meeting_Alternate_Hosts__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_Alternate_Hosts__c</fullName>
    <description>Created By: CC
Purpose: Comma Separated list of emails of default Alternate Hosts for WFT Class Meetings.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Comma Separated list of emails of default Alternate Hosts for WFT Class Meetings.</inlineHelpText>
    <label>Zoom Meeting Alternate Hosts</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WFT_Custom_Settings__c/fields/Zoom_Meeting_Host__c.field-meta.xml
<CustomField>
    <fullName>Zoom_Meeting_Host__c</fullName>
    <description>Created By: CC
Purpose: Store Email or Zoom Id of user who be the default host for WFT Zoom Meetings.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Store Email or Zoom Id of user who be the default host for WFT Zoom Meetings. Only one user can be host.</inlineHelpText>
    <label>Zoom Meeting Host</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ZoomService.cls
public class ZoomService {
    
    @InvocableMethod(callout=true label='Create Zoom Meeting From Class' description='Creates a Zoom Link and populates Zoom Link field on class.' category='Class')
    public static List<Class__c> createMeeting(List<Class__c> classes) {
        for(Class__c c : classes) {
            ZoomMeeting meeting = createZoomMeetingObject(c);
            System.debug(meeting);
            Map<String, Object> zoomResponse = createMeetingAndParseResponse(meeting);
            if(! zoomResponse.isEmpty()) {
                c.Zoom_Link__c = (String) zoomResponse.get('join_url');
                Long zoomId = (Long) zoomResponse.get('id');
                c.Zoom_Meeting_Id__c = String.valueOf(zoomId);
            }
        }
        return classes;
    }
    
    public static ZoomMeeting createZoomMeetingObject(Class__c c) {
        ZoomMeeting meeting = new ZoomMeeting();
        WFT_Custom_Settings__c customSetting =  WFT_Custom_Settings__c.getOrgDefaults();
        System.debug(customSetting.Zoom_API_User__c);
        meeting.userId = customSetting.Zoom_API_User__c;
        meeting.topic = c.Market__c + ' ' + c.Display_Name__c + ' ' + c.Time_Zone__c;
        meeting.type = 8;
        meeting.start_time = dateTime.newInstanceGmt(c.Start_Date__c, Time.newInstance(18, 0, 0, 0));
        meeting.duration = 180;
        System.debug(customSetting.Zoom_Meeting_Host__c);
        meeting.schedule_for = customSetting.Zoom_Meeting_Host__c;

        switch on c.Time_Zone__c {
            when 'Eastern' {
                meeting.timezone = 'America/New_York';
            }
            when 'Central' {
                meeting.timezone = 'America/Chicago';
            }
            when 'Mountain' {
                meeting.timezone = 'America/Denver';
            }
            when else {
                meeting.timezone = 'America/Los_Angeles';
            }
        }
        meeting.default_password = true;
        meeting.agenda = c.Class_Description__c;
        meeting.recurrence.type = 2;
        meeting.recurrence.repeat_interval = 1;
        
        switch on c.Class_Nights__c {
            when 'Monday / Wednesday' {
                meeting.recurrence.weekly_days = '2,4';
            }
            when 'Tuesday / Thursday' {
                meeting.recurrence.weekly_days = '3,5';
            }
            when 'Wednesday' {
                meeting.recurrence.weekly_days = '4';
            }
            when else {
                meeting.recurrence.weekly_days = '2,3,4,5';
            }
        }
        
        meeting.recurrence.end_date_time = dateTime.newInstanceGmt(c.End_Date__c,  Time.newInstance(21, 0, 0, 0));
        meeting.settings.host_video = false;
        meeting.settings.participant_video = false;
        meeting.settings.mute_upon_entry = true;
        meeting.settings.waiting_room = true;
        meeting.settings.alternative_hosts = customSetting.Zoom_Meeting_Alternate_Hosts__c;

        return meeting;
    }
    
    private static Map<String,Object> createMeetingAndParseResponse(ZoomMeeting meeting) {
        Map<String,Object> responseMap = new Map<String,Object>();
        HttpResponse response = createMeeting(meeting);
        System.debug(response.getStatusCode());

        if (response.getStatusCode() == 201) {
            System.debug('Success');
            responseMap = (Map<String,Object>)JSON.deserializeUntyped(response.getBody());
            
        } else {
            System.debug('Failure');
            System.debug(response.getBody());
        }
        return responseMap;
    }

    private static HttpResponse createMeeting(ZoomMeeting  meeting) {
        HttpRequest req = new HttpRequest();
        WFT_Custom_Settings__c customSetting =  WFT_Custom_Settings__c.getOrgDefaults();
        req.setEndpoint('https://api.zoom.us/v2/users/' + customSetting.Zoom_API_User__c + '/meetings');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        //Custom Setting HERE
        String auth = 'Bearer ' + customSetting.Zoom_API_JWT__c;
        req.setHeader('Authorization', auth);
        String payload = JSON.serialize(meeting);
        req.setBody(payload);
        
        if ( customSetting.Most_Recent_Zoom_Meeting_API_Call__c != System.now().date()) {
            customSetting.Most_Recent_Zoom_Meeting_API_Call__c = System.now().date();
            customSetting.Daily_User_Zoom_Meeting_API_Calls__c = 0;
        }
        Http http = new Http();
        HttpResponse res = new HttpResponse();
        res = http.send(req);
        customSetting.Daily_User_Zoom_Meeting_API_Calls__c++;
        update customSetting;
        return res;
    }

    // public static String createJWT() {
    //     String apiKey = 'HjYj1tT5SS6yzSOEFVsBmA';
    //     String secretKey = 'kBc1nBiPpMKVJZvqlU5AMGZ8bpI4OMC3W5uH';
    //     DateTime tokenExpiration = (DateTime) System.today() + 30;
    //     System.debug(tokenExpiration);
    //     System.debug(tokenExpiration.getTime().format());
        
    //     String header = '{ "alg": "HS256","typ": "JWT"}';
    //     header = EncodingUtil.base64Encode(Blob.valueOf(header));
    //     System.debug(header);
        
    //     String payload ='{"iss": "' + apiKey + '","exp": ' + tokenExpiration.getTime().format() +'}';
    //     payload = EncodingUtil.base64Encode(Blob.valueOf(payload));
    //     System.debug(payload);
        
    //     String input = header + '.' + payload;

    //     input = input.replace('+', '-');
    //     input = input.replace('/', '_');
    //     while ( input.endsWith('=')){
    //         input = input.subString(0,input.length()-1);
    //     }

    //     System.debug(input);
        
    //     return 'token';
    // }

     public class ZoomMeeting {
        public String userId;
        public String topic;
        public Integer type;
        public Boolean pre_schedule;
        public Datetime start_time;
        public Integer duration;
        public String schedule_for;
        public String timezone;
        public String password; 
        public Boolean default_password; 
        public String agenda; 
        MeetingRecurrence recurrence = new MeetingRecurrence(); 
        MeetingSettings settings = new MeetingSettings();   
    }

   public class MeetingRecurrence {
        public Integer type;
        public Integer repeat_interval;
        public String weekly_days;
        public Integer monthly_day;
        public Integer monthly_week;
        public Integer monthly_week_day;
        public Integer end_times;
        public Datetime end_date_time;
   }

   public class MeetingSettings {
        public Boolean host_video;
        public Boolean participant_video;
        public Boolean cn_meeting;
        public Boolean in_meeting;
        public Boolean join_before_host;
        public Boolean mute_upon_entry;
        public Boolean watermark;
        public Boolean use_pmi;
        public Integer approval_type;
        public Integer registration_type;
        public String audio;
        public String auto_recording;
        public String alternative_hosts;
        public Boolean waiting_room;
        public Boolean enforce_login;
        public String enforce_login_domains;
    }
}