force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Attendance_Type__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Type__c</fullName>
    <label>Attendance Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClassTriggerHandler.cls
public class ClassTriggerHandler extends TriggerHandler {
    private List<Class__c> newList;
	private List<Class__c> oldList;
	private Map<Id, Class__c> newMap;
	private Map<Id, Class__c> oldMap;

	public override void setupNewList() {
		newList = (List<Class__c>) newSObjList;
	}

	public override void setupOldList() {
		oldList = (List<Class__c>) oldSObjList;
	}

	public override void setupNewMap() {
		newMap = new Map<Id, Class__c>(newList);
	}

	public override void setupOldMap() {
		oldMap = new Map<Id, Class__c>(oldList);
	}

	public override void onAfterUpdate() {

	}

	public override void onAfterInsert() {
		Set<Id> classIdsZoom = new Set<Id>();

		//We only want to operate on the Classes who are type Virtual.
		for (Class__c singleClass : newList) {
            if (singleClass.Attendance_Type__c == 'Virtual') {
            	classIdsZoom.add(singleClass.id);
                System.debug(classIdsZoom);
            }            
		}

		if (classIdsZoom.size() > 0) {
			runClassBatch(classIdsZoom);
		}    
	}
    
    private void runClassBatch(Set<Id> classIdsZoom) {
		ZoomBatchUpdate b = new ZoomBatchUpdate();
		b.classIds = classIdsZoom;
		System.debug(b.classIds);
		if (!System.isBatch()) {
            System.debug('Get Here');
			Database.executeBatch(b, 1);
		}
	}
}