force-app/main/default/objects/Market__c/Market__c.object-meta.xml
<CustomObject>
    <description>Created By: CC
Department: BW
Purpose: Contains information on markets including description and postal codes.</description>
    <label>Market</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Market__c/fields/PostalCodes__c.field-meta.xml
<CustomField>
    <fullName>PostalCodes__c</fullName>
    <description>Created By: CC 
Department: 
BW Purpose: List of postal codes associated with a market.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip/Postal Codes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Public_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Public_Knowledge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created By: CC
Purpose: Signify if a Market is public knowledge or not.</description>
    <inlineHelpText>Can the public know this Bitwise market exists?</inlineHelpText>
    <label>Public Knowledge</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Market__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: CC
Department: BW
Purpose: Track the status of the market.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddressUtilityTests.cls
@isTest
public class AddressUtilityTests {
    @TestSetup
    static void setup() {
		Market__c market = new Market__c(Name = 'Fresno',
								Public_Knowledge__c = true, 
								Status__c = 'Active', 
								PostalCodes__c = '93721,93725');
		insert market;
        
    }

	@isTest
	public static void getMarketTest() {
		System.assertEquals('Fresno', AddressUtility.getMarket('93721'));
	}
	@isTest
	public static void getPublicKnowledgeMarketTest() {
		System.assertEquals('Fresno', AddressUtility.getPublicKnowledgeMarket('93721'));
	}
	@isTest
	public static void getMarketTestMarketNotFound() {
		System.assertEquals('Other', AddressUtility.getMarket('937'));
	}

	@isTest
	public static void getMarketTestNoActiveMarkets() {
		Market__c market = [SELECT Id, Name, Status__c FROM Market__c WHERE Status__c = 'Active'];
		market.Status__c = 'Inactive';
		update market;
		System.assertEquals('Other', AddressUtility.getMarket('937'));
	}
    
    @isTest
	public static void getMarketInvocableNotFound() {
        
        List<String> postalCodes = new List<String>{'937'};
		List<String> marketNames = AddressUtility.getMarket(postalCodes);
		System.assertEquals('Other', marketNames[0]);
	}
    @isTest
    public static void getMarketInvocablePostalCodeFound() {
        
        List<String> postalCodes = new List<String>{'93721'};
		List<String> marketNames = AddressUtility.getMarket(postalCodes);
		System.assertEquals('Fresno', marketNames[0]);
	}
	@isTest
	 public static void getMarketInvocableMultiplePostalCodes() {
        
        List<String> postalCodes = new List<String>{'93721','93725'};
		List<String> marketNames = AddressUtility.getMarket(postalCodes);
		System.assertEquals(2, marketNames.size());
	}
	@isTest
	public static void getMarketInvocableBlankPostalCode() {
        
        List<String> postalCodes = new List<String>{'93721','','93725'};
		List<String> marketNames = AddressUtility.getMarket(postalCodes);
		System.assertEquals(3, marketNames.size());
	}
	 @isTest
	public static void getMarketInvocableNoMarkets() {
        
        List<String> postalCodes = new List<String>{'93721'};
		delete [SELECT Id FROM Market__c WHERE Name = 'Fresno'];
		System.assertEquals(null, AddressUtility.getMarket(postalCodes));
	}

	 @isTest
	public static void getMarketInvocableInputNull() {
		 List<String> postalCodes;
		System.assertEquals(null, AddressUtility.getMarket(postalCodes));
	}

	
	@isTest
	public static void getUSStatesTest() {
		System.assertEquals(50, AddressUtility.getUSStates().size());
	}

	@isTest
	public static void getUSStatesSelectOptionsTest() {
		System.assertEquals(51, AddressUtility.getUSStatesSelectOptions().size());
	}
}