force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stripe Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Day Pass</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant</fullName>
            </value>
            <value>
                <fullName>Hashtag + Lift</fullName>
            </value>
            <value>
                <fullName>Individual Yearly</fullName>
            </value>
            <value>
                <fullName>Student Yearly</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant + Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Charge_ID__c.field-meta.xml
<CustomField>
    <fullName>Charge_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Charge ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>The ID of the Stripe Customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>The ID of the Subscription in Stripe.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Created By: CC
Department: WFT
Purpose: Note type of payment.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit/Debit</fullName>
                <default>true</default>
                <label>Credit/Debit</label>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>CC Hashtag End date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Length__c.field-meta.xml
<CustomField>
    <fullName>Length__c</fullName>
    <formula>(End__c - Start__c) * 24 * 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>CC Hashtag Membership that Reservations are Associated with Manually</description>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Room_Type_Formula__c.field-meta.xml
<CustomField>
    <fullName>Room_Type_Formula__c</fullName>
    <formula>TEXT( Space__r.Reservation_Room_Type__c )</formula>
    <label>Room Type Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>CC Hashtag Start date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>There&apos;s a known issue about DATEVALUE() with times near midnight:
https://success.salesforce.com/issues_view?id=a1p30000000Su0tAAC</description>
    <formula>DATEVALUE(Start__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Way to mark the current status Flow/Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripeMembershipChargeBatch.cls
public class StripeMembershipChargeBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    static Map<Id, Decimal> chargeByMembership;

    public static final String DEPARTMENT = 'Cowork';

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('Running StripeMembershipChargeBatch.start()');
        chargeByMembership = getChargeAmounts(Date.today().addDays(-1)); //Charge for yesterday.
        Set<Id> memberships = chargeByMembership.keySet();
        System.debug('Charging for: '+memberships);
        String query = 'SELECT Name, Id, Contact__c, Contact__r.Cowork_Stripe_Customer_Id__c, Stripe_Subscription_Id__c FROM Membership__c WHERE Id IN :memberships'; 
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Membership__c> memberships) {
        System.debug('Running StripeMembershipChargeBatch.execute()');
        Date relevantDate = Date.today().addDays(-1);
        chargeByMembership = getChargeAmounts(relevantDate); //Charge for yesterday.
        System.debug('Starting charges.');
        for (Membership__c membership : memberships) {
            String stripeId = membership.Contact__r.Cowork_Stripe_Customer_Id__c;
            Decimal amount = chargeByMembership.get(membership.Id);
            System.debug('Charging '+membership.Id + ' $'+String.valueOf(amount));
            String chargeId = StripePaymentService.getInstance().chargeCustomer(DEPARTMENT, stripeId, null, amount, 'Conference Room Booking Fee');


            Payment_Result__c result = new Payment_Result__c(
                Membership__c = membership.Id,
                Charge_ID__c = chargeId,
                Contact__c = membership.Contact__c,
                Customer_ID__c = membership.Contact__r.Cowork_Stripe_Customer_Id__c,
                Subscription_ID__c = membership.Stripe_Subscription_Id__c,
                Source__c = 'End-Of-Day Charges'
            );

            if(chargeId.contains('error')) {
                result.Status__c = 'error';
            } else {
                result.Status__c = 'success';

                List<Reservation__c> reservations = [SELECT Id, Membership__c, Room_Type_Formula__c, Start__c, End__c, Start_Date__c, Length__c 
                                             FROM Reservation__c 
                                             WHERE Start_Date__c = :relevantDate AND
                                                   Status__c = 'Active' AND
                                                   Membership__c = :membership.Id];
                
                for (Reservation__c res : reservations) {
                    res.Status__c = 'Charged';
                }

                update reservations;
            }

            PaymentResultProcessingService.upsertPaymentResult(result);
        }
        System.debug('Done charging.');
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Running StripeMembershipChargeBatch.finish()');
    }

    /**
     * Pulls all important reservations and the price of them.
     */
    public Map<Id, Decimal> getChargeAmounts(Date day) {
        System.debug('Getting Charge Amounts for ' + string.valueOf(day));


        //Get reservations relating to today, and add up the amount of time they spend in each type of room.
        Map<Id, Integer> conferenceMinutes = new Map<Id, Integer>(); //Maps the ID of the membership to the amount that member spent in a conference room.
        Map<Id, Integer> podcastMinutes = new Map<Id, Integer>(); //Maps the ID of the membership to the amount that member spent in a podcast booth.
        Set<Id> memberIds = new Set<Id>();


        List<Reservation__c> reservations = [SELECT Id, Membership__c, Room_Type_Formula__c, Start__c, End__c, Start_Date__c, Length__c 
                                             FROM Reservation__c 
                                             WHERE Start_Date__c = :day AND
                                                   Status__c = 'Active'];

        System.debug('Iterating through reservations.');

        for (Reservation__c reservation : reservations) {
            System.debug('----- ' + reservation);
            Id memberId = reservation.Membership__c;
            memberIds.add(memberId);

            if (reservation.Room_Type_Formula__c == 'Conference Room') {

                //If the member isn't in the map, put them there.
                if (!conferenceMinutes.containsKey(memberId)) {
                    conferenceMinutes.put(memberId, 0);
                }

                conferenceMinutes.put(memberId, (Integer)(conferenceMinutes.get(memberId)+reservation.Length__c));

            } else if (reservation.Room_Type_Formula__c == 'Podcast Booth') {

                //If the member isn't in the map, put them there.
                if (!podcastMinutes.containsKey(memberId)) {
                    podcastMinutes.put(memberId, 0);
                }

                podcastMinutes.put(memberId, (Integer)(podcastMinutes.get(memberId)+reservation.Length__c));
            }
        }

        System.debug('Done iterating through reservations.');
        System.debug('----- MemberIds' + memberIds);
        System.debug('----- Conference Minutes: ' + conferenceMinutes);
        System.debug('----- Podcast Minutes: '+ podcastMinutes);

        Map<Id, Decimal> output = new Map<Id, Decimal>();

        //Query for memberships so you can charge appropriately.
        Map<Id, Membership__c> memberships = new Map<Id, Membership__c>([SELECT Id, Type__c, Contact__r.Cowork_Member__c FROM Membership__c WHERE Id IN :memberIds]);


        System.debug('Iterating through memberships.');
        for (Id memberId : memberIds) {
            Decimal amount = 0;
            Boolean isMember = memberships.get(memberId).Contact__r.Cowork_Member__c;
            Boolean isGroup = memberships.get(memberId).Type__c == 'Group' ? true : false;

            System.debug('Member '+memberId+' is member = ' + String.valueOf(isMember) + 'is Group = ' + String.valueOf(isGroup));

            if (conferenceMinutes.containsKey(memberId)) {
                System.debug('Conference Minutes: ' + conferenceMinutes.get(memberId));
                //If Group they get 4 free hours a day not 1
                if ( conferenceMinutes.get(memberId) > 240 && isMember && isGroup){
                    amount += (((Decimal)conferenceMinutes.get(memberId) - 240)/60) * Constants.conferenceRoomMemberPrice;
                    
                } else if (conferenceMinutes.get(memberId) > 60 && isMember && !isGroup) {
                    //If they book more than an hour, take 60 minutes off their booking and charge the correct amount. 
                    amount += (((Decimal)conferenceMinutes.get(memberId) - 60)/60) * Constants.conferenceRoomMemberPrice;
                } else if (!isMember) {
                    amount += (((Decimal)conferenceMinutes.get(memberId))/60) * Constants.conferenceRoomNonMemberPrice;
                }
            }

            if (podcastMinutes.containsKey(memberId)) {
                System.debug('Podcast Minutes: ' + podcastMinutes.get(memberId));
                Decimal chargeNumber = isMember? Constants.podcastBoothMemberPrice : Constants.podcastBoothNonMemberPrice;
                amount += ((Decimal)podcastMinutes.get(memberId)/180) * chargeNumber;
            }

            if (amount > 0) {
                output.put(memberId, amount);
            }
        }

        return output;
    }
}