force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by: CMP 
Business Unit: Cowork
Purpose: to link Membership to Accounts</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Membership_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_End_Date__c</fullName>
    <description>CC Hashtag Mark End Date of Memberships Automatic</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Membership_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Start_Date__c</fullName>
    <description>CC Hashtag Membership Start Date Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Day Pass</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant</fullName>
            </value>
            <value>
                <fullName>Hashtag + Lift</fullName>
            </value>
            <value>
                <fullName>Individual Yearly</fullName>
            </value>
            <value>
                <fullName>Student Yearly</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant + Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>CC Hashtag End date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>CC Hashtag Membership that Reservations are Associated with Manually</description>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC Hashtag Link Space to Reservation Visualforce</description>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>CC Hashtag Start date and time of reservation Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Way to mark the current status Flow/Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of a given space</description>
    <inlineHelpText>What is the status of the space?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TabletReservationTests.cls
@isTest
public class TabletReservationTests {
    static testMethod void testMethods() {
        account newAccount = new account(name = 'TestAccount');
        insert newAccount;
        contact newContact = new contact(firstName = 'test', lastName = 'tester', account = newAccount, email = 'test@test.com');
        insert newContact;
        //membership__c newMember = new membership__c(status__c = 'active', account__c = newAccount.id, contact__c = newContact.id, name = '123', Membership_Start_Date__c = system.TODAY(), Membership_End_Date__c = system.TODAY() + 30, type__c = 'individual');
        //insert newMember;
        space__c newSpace = new space__c(name = 'Test', status__c = 'available');
        insert newSpace;
        //reservation__c currentReservation = new reservation__c(contact__c = newContact.id, membership__c = newMember.id, space__c = newSpace.id, start__c = system.now(), end__c = system.now() + 1);
        //insert currentReservation;
		ApexPages.currentPage().getParameters().put('id', newSpace.id);
        TabletReservation tr = new TabletReservation();
		system.assertEquals(tr.getToday, system.today());
        system.assertEquals(tr.currentTime, system.now());
        system.assertEquals(tr.currentRoom.id, newSpace.id);
    }
}