force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>CC Hashtag Membership that Reservations are Associated with Manually</description>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC Hashtag Link Space to Reservation Visualforce</description>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Way to mark the current status Flow/Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Calendar_ID__c.field-meta.xml
<CustomField>
    <fullName>Calendar_ID__c</fullName>
    <description>JA
Business Unit: Hashtag
Purpose: Store Related Google Calendar Id
Population: Manual</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Calendar ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Space__c/fields/Cowork_Reservable__c.field-meta.xml
<CustomField>
    <fullName>Cowork_Reservable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, space status will always be set to available.</inlineHelpText>
    <label>Cowork Reservable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Space__c/fields/Reservation_Room_Type__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Room_Type__c</fullName>
    <description>Created By: DA
Business Unit: Hashtag
Purpose: Defines the type of reservation space</description>
    <label>Reservation Room Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference Room</fullName>
            </value>
            <value>
                <fullName>Podcast Booth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Space__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of a given space</description>
    <inlineHelpText>What is the status of the space?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookConferenceRoomControllerTests.cls
@isTest
public class BookConferenceRoomControllerTests {
    static BookConferenceRoomController cont;
    static Space__c conferenceRoom;
    static Space__c podcastBooth;
    static Contact contactRecord;

    public static void setup() {
        GoogleCalendarService.instance = new GoogleCalendarServiceMock();

        //Override the constants file to ensure the logic is tested the same way, regardless of constants. 
        Constants.blockLength = 30;
        Constants.maxReservationLength = 300;

        conferenceRoom = new Space__c(
            Name='Test Conference Room', 
            Cowork_Reservable__c = true, 
            Reservation_Room_Type__c = 'Conference Room', 
            Calendar_Id__c = 'Test_Calendar_Id'
        );
        podcastBooth = new Space__c(
            Name='Test Podcast Booth', 
            Cowork_Reservable__c = true, 
            Reservation_Room_Type__c = 'Podcast Booth', 
            Calendar_Id__c = 'Test_Calendar_Id'
        );
        insert new List<Space__c>{conferenceRoom, podcastBooth};

        contactRecord = new Contact(
            LastName = 'Test',
            FirstName = 'Unit',
            Email = 'unittest@example.com'
        );
        insert contactRecord;
    }

    @isTest
    public static void testSetup() {
        setup();
    }

    @isTest
    public static void testSetTimeOptions() {
        setup();

        cont = new BookConferenceRoomController();
        
        Test.startTest();
        cont.setTimeOptions();
        Test.stopTest();

        System.assertEquals(11, cont.timeOptions.size());
        System.assertEquals('0', cont.timeOptions[0].getValue());
        System.assertEquals('30', cont.timeOptions[1].getValue());
        System.assertEquals('60', cont.timeOptions[2].getValue());
    }

    @isTest
    public static void testConstructor() {
        setup();
        
        Test.startTest();
        cont = new BookConferenceRoomController();
        Test.stopTest();

        System.assertEquals(Date.today(), cont.apptDate);
        System.assertEquals('Conference Room', cont.roomType);
    }

    @isTest
    public static void testRenderFormConferenceRoom() {
        setup();

        cont = new BookConferenceRoomController();
        cont.duration=60;
        cont.roomType = 'Conference Room';
        
        Test.startTest();
        cont.renderForm();
        Test.stopTest();

        System.assertEquals(1, cont.availableTimeSlots.keySet().size());
        System.assertEquals(conferenceRoom.Id, new List<Id>(cont.availableTimeSlots.keySet())[0]);
    }

    @isTest
    public static void testRenderFormPodcastBooth() {
        setup();

        cont = new BookConferenceRoomController();
        cont.roomType = 'Podcast Booth';
        
        Test.startTest();
        cont.renderForm();
        Test.stopTest();

        System.assertEquals(180, cont.duration);
        System.assertEquals(1, cont.availableTimeSlots.keySet().size());
        System.assertEquals(podcastBooth.Id, new List<Id>(cont.availableTimeSlots.keySet())[0]);
    }

    @isTest
    public static void testSubmitFormExistingMembership() {
        setup();

        PageReference pr = Page.BookConferenceRoom;
        Date d = Date.today();
        DateTime dtObj = Datetime.newInstance(d.year(), d.month(), d.day(), 6,0,0);
        String dtString = dtObj.format('EEE MMM dd HH:mm:ss') + ' GMT ' +String.valueOf(dtObj.year());
        // pr.getParameters().put('chosen_time', conferenceRoom.Id + '.' + dtString);
        // Test.setCurrentPage(pr);

        Membership__c membership = new Membership__c(
            Contact__c = contactRecord.Id,
            Status__c = 'Active'
        );

        insert membership;



        cont = new BookConferenceRoomController();
        cont.email = 'unittest@example.com';
        cont.duration = 60;


        Test.startTest();
        String nextPr = BookConferenceRoomController.submitFormRemoting(conferenceRoom.Id + '.' + dtString, 'unittest@example.com','60');
        Test.stopTest();

        List<Reservation__c> resList = [SELECT Id, Membership__c FROM Reservation__c];


        System.assertEquals(1, resList.size());
        System.assertEquals(membership.Id, resList[0].Membership__c);
    }

    @isTest
    public static void testSubmitFormNoMembership() {
        setup();

        PageReference pr = Page.BookConferenceRoom;
        Date d = Date.today();
        DateTime dtObj = Datetime.newInstance(d.year(), d.month(), d.day(), 6,0,0);
        String dtString = dtObj.format('EEE MMM dd HH:mm:ss') + ' GMT ' +String.valueOf(dtObj.year());
        pr.getParameters().put('chosen_time', conferenceRoom.Id + '.' + dtString);
        Test.setCurrentPage(pr);

        cont = new BookConferenceRoomController();
        cont.email = 'unittest@example.com';
        cont.duration = 60;


        Test.startTest();
        String nextPr = BookConferenceRoomController.submitFormRemoting(conferenceRoom.Id + '.' + dtString, 'unittest@example.com','60');
        Test.stopTest();


        System.assert(nextPr.contains('payment'));
    }

}