force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Charge_ID__c.field-meta.xml
<CustomField>
    <fullName>Charge_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Charge ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentResultProcessingServiceTests.cls
@isTest 
public class PaymentResultProcessingServiceTests {
    

    @isTest
    public static void testInsertNewPayment() {
        
        Payment_Result__c res = new Payment_Result__c();
        
        Test.startTest();
        Payment_Result__c upserted = PaymentResultProcessingService.upsertPaymentResult(res);
        Test.stopTest();

        System.assertNotEquals(null, upserted);
        System.assertNotEquals(null, upserted.Id);
    }

    @isTest
    public static void testInsertNewPaymentWithChargeId() {
        
        Payment_Result__c res = new Payment_Result__c(Charge_ID__c = 'TEST_CHARGE');
        
        Test.startTest();
        Payment_Result__c upserted = PaymentResultProcessingService.upsertPaymentResult(res);
        Test.stopTest();

        System.assertNotEquals(null, upserted);
        System.assertNotEquals(null, upserted.Id);
    }

    @isTest
    public static void testUpdateResultWithId() {
        
        Payment_Result__c res = new Payment_Result__c();

        insert res;

        res.Charge_ID__c = 'TEST_CHARGE';
        
        Test.startTest();
        Payment_Result__c upserted = PaymentResultProcessingService.upsertPaymentResult(res);
        Test.stopTest();

        System.assertNotEquals(null, upserted);
        System.assertNotEquals(null, upserted.Id);
        System.assertEquals('TEST_CHARGE', upserted.Charge_ID__c);
    }

    @isTest
    public static void testUpdateResultWithChargeId() {
        
        Payment_Result__c res = new Payment_Result__c();
        res.Charge_ID__c = 'TEST_CHARGE';
        insert res;

        Payment_Result__c newRes = new Payment_Result__c(Charge_ID__c = 'TEST_CHARGE', Amount__c = 10);
        
        Test.startTest();
        Payment_Result__c upserted = PaymentResultProcessingService.upsertPaymentResult(newRes);
        Test.stopTest();

        System.assertNotEquals(null, upserted);
        System.assertEquals(res.Id, upserted.Id);
        System.assertEquals('TEST_CHARGE', upserted.Charge_ID__c);
    }    
}