force-app/main/default/objects/Cowork_Membership_Types__c/Cowork_Membership_Types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Cowork Membership Types</label>
</CustomObject>

force-app/main/default/objects/Cowork_Membership_Types__c/fields/Pricing_Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The ID (from Stripe) to specify the Pricing Plan (e.g. &apos;regular-monthly&apos;)</inlineHelpText>
    <label>Pricing Plan ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cowork_Room_Booking__c/Cowork_Room_Booking__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores data about limits and pricing for Cowork.</description>
    <label>Cowork Room Booking</label>
</CustomObject>

force-app/main/default/objects/Cowork_Room_Booking__c/fields/Conference_Room_Non_Member_Price__c.field-meta.xml
<CustomField>
    <fullName>Conference_Room_Non_Member_Price__c</fullName>
    <label>Conference Room Non-Member Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cowork_Room_Booking__c/fields/Podcast_Booth_Non_Member_Price__c.field-meta.xml
<CustomField>
    <fullName>Podcast_Booth_Non_Member_Price__c</fullName>
    <label>Podcast Booth Non-Member Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stripe Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <description>Created By: RG
Business Unit: Hashtag
Purpose: To Reserve conference and podcast booth at the Hashtag</description>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <description>CC Hashtag Membership that Reservations are Associated with Manually</description>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC Hashtag Link Space to Reservation Visualforce</description>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Way to mark the current status Flow/Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Cowork_Reservable__c.field-meta.xml
<CustomField>
    <fullName>Cowork_Reservable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, space status will always be set to available.</inlineHelpText>
    <label>Cowork Reservable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Space__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of a given space</description>
    <inlineHelpText>What is the status of the space?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentControllerTests.cls
@isTest
public class PaymentControllerTests {
    static PaymentController cont;
    static Space__c space;

    public static void setup() {
        
        insert new Cowork_Room_Booking__c (
            Podcast_Booth_Member_Price__c = 10,
            Podcast_Booth_Non_Member_Price__c = 10,
            Conference_Room_Member_Price__c = 10,
            Conference_Room_Non_Member_Price__c = 10
        );

        insert new Cowork_Membership_Types__c(
            Name = 'Individual',
            Label__c = 'Individual',
            Pricing_Plan_Id__c = 'Individual-Monthly',
            Sort_Order__c = 1
        );

        insert new Cowork_Membership_Types__c(
            Name = 'Group',
            Label__c = 'Group',
            Pricing_Plan_Id__c = 'Group-Monthly',
            Sort_Order__c = 0
        );

        insert new Cowork_Membership_Types__c(
            Name='DayPass',
            Label__c = 'Day Pass',
            Sort_Order__c = 2
        );

        space = new Space__c(
            Name = 'Passing Unit Tests',
            Cowork_Reservable__c = true
        );
        insert space;

        cont = new PaymentController();

        StripePaymentServiceMock mock = new StripePaymentServiceMock();
        StripePaymentService.instance = mock;
        
        GoogleCalendarServiceMock gCalMock = new GoogleCalendarServiceMock();
        GoogleCalendarService.instance = gCalMock;
        
        cont.paymentFirstName = 'Unit';
        cont.paymentLastName = 'Test 1';
        cont.paymentEmail = 'unit@test.com';
        cont.paymentPhone = '1235551234';
        cont.memberCompany = 'Unit Tests R Us';
        cont.memberCity = 'Townsville';
        cont.memberState = 'California';
        cont.discountCode = '';
        cont.membershipType = 'Individual';
        cont.codeOfConductValue = true;
        cont.covidPolicyValue = true;
        insert TestDataFactory.createGateway('Cowork');
    }

    @isTest
    public static void testProcessNew() {
        // A completely new user signs up for a membership.
        setup();

        PageReference currentPage = Page.Payment;
        currentPage.getParameters().put('card_token', 'TOKEN');
        Test.setCurrentPage(currentPage);
        
        
        Test.startTest();
        PageReference result = cont.processToken();
        Test.stopTest();

        List<Contact> conts = [SELECT Id, AccountId, Cowork_Stripe_Customer_Id__c FROM Contact];
        System.assertEquals(1, conts.size());
        System.assertEquals('CUSTOMER_ID', conts[0].Cowork_Stripe_Customer_Id__c);
        List<Account> accts = [SELECT Id FROM Account];
        System.assertEquals(1, accts.size());
        System.assertEquals(accts[0].Id, conts[0].AccountId, 'The created Contact does not link to the created account.');
        List<Membership__c> memberships = [SELECT Id, Stripe_Subscription_Id__c FROM Membership__c];
        System.assertEquals(1, memberships.size());
        System.assertEquals('SUBSCRIPTION_ID', memberships[0].Stripe_Subscription_Id__c);
        // List<Payment_Result__c> results = [SELECT Id, Status__c FROM Payment_Result__c];
        // System.assertEquals(1, results.size());
        // System.assertEquals('success', results[0].Status__c);
    }

    @isTest
    public static void testProcessExistingContact() {
        // A user with an existing contact signs up for a membership.
        setup();

        Contact c = new Contact(LastName = 'Test 1', FirstName='Unit', email='unit@test.com', Cowork_Stripe_Customer_Id__c = 'CUSTOMER_ID');
        insert c;

        PageReference currentPage = Page.Payment;
        currentPage.getParameters().put('card_token', 'TOKEN');
        Test.setCurrentPage(currentPage);
        
        
        Test.startTest();
        PageReference result = cont.processToken();
        Test.stopTest();

        List<Contact> conts = [SELECT Id, AccountId, Cowork_Stripe_Customer_Id__c FROM Contact];
        System.assertEquals(1, conts.size());
        System.assertEquals('CUSTOMER_ID', conts[0].Cowork_Stripe_Customer_Id__c);
        List<Account> accts = [SELECT Id FROM Account];
        System.assertEquals(1, accts.size());
        System.assertEquals(accts[0].Id, conts[0].AccountId, 'The created Contact does not link to the created account.');
        List<Membership__c> memberships = [SELECT Id, Stripe_Subscription_Id__c FROM Membership__c];
        System.assertEquals(1, memberships.size());
        System.assertEquals('SUBSCRIPTION_ID', memberships[0].Stripe_Subscription_Id__c);
        // List<Payment_Result__c> results = [SELECT Id, Status__c FROM Payment_Result__c];
        // System.assertEquals(1, results.size());
        // System.assertEquals('success', results[0].Status__c);
    }

    @isTest
    public static void testProcessExistingAccount() {
        // A user with an existing contact signs up for a membership.
        setup();

        Account acct = new Account(Name='Unit Tests R Us', BillingCity = 'Townsville', BillingState = 'California');

        insert acct;

        PageReference currentPage = Page.Payment;
        currentPage.getParameters().put('card_token', 'TOKEN');
        Test.setCurrentPage(currentPage);
        
        
        Test.startTest();
        PageReference result = cont.processToken();
        Test.stopTest();

        List<Contact> conts = [SELECT Id, AccountId, Cowork_Stripe_Customer_Id__c FROM Contact];
        System.assertEquals(1, conts.size());
        System.assertEquals('CUSTOMER_ID', conts[0].Cowork_Stripe_Customer_Id__c);
        List<Account> accts = [SELECT Id FROM Account];
        System.assertEquals(1, accts.size());
        System.assertEquals(accts[0].Id, conts[0].AccountId, 'The created Contact does not link to the created account.');
        List<Membership__c> memberships = [SELECT Id, Stripe_Subscription_Id__c FROM Membership__c];
        System.assertEquals(1, memberships.size());
        System.assertEquals('SUBSCRIPTION_ID', memberships[0].Stripe_Subscription_Id__c);
        // List<Payment_Result__c> results = [SELECT Id, Status__c FROM Payment_Result__c];
        // System.assertEquals(1, results.size());
        // System.assertEquals('success', results[0].Status__c);
    }

    @isTest
    public static void testProcessExistingAccountContact() {
        // A user with an existing contact signs up for a membership.
        setup();

        Account acct = new Account(Name='Unit Tests R Us', BillingCity = 'Townsville', BillingState = 'California');
        
        insert acct;
        Contact c = new Contact(LastName = 'Test 1', FirstName='Unit', email='unit@test.com', AccountId = acct.Id);
        insert c;

        PageReference currentPage = Page.Payment;
        currentPage.getParameters().put('card_token', 'TOKEN');
        Test.setCurrentPage(currentPage);
        
        
        Test.startTest();
        PageReference result = cont.processToken();
        Test.stopTest();

        List<Contact> conts = [SELECT Id, AccountId, Cowork_Stripe_Customer_Id__c FROM Contact];
        System.assertEquals(1, conts.size());
        System.assertEquals('CUSTOMER_ID', conts[0].Cowork_Stripe_Customer_Id__c);
        List<Account> accts = [SELECT Id FROM Account];
        System.assertEquals(1, accts.size());
        System.assertEquals(accts[0].Id, conts[0].AccountId, 'The created Contact does not link to the created account.');
        List<Membership__c> memberships = [SELECT Id, Stripe_Subscription_Id__c FROM Membership__c];
        System.assertEquals(1, memberships.size());
        System.assertEquals('SUBSCRIPTION_ID', memberships[0].Stripe_Subscription_Id__c);
        // List<Payment_Result__c> results = [SELECT Id, Status__c FROM Payment_Result__c];
        // System.assertEquals(1, results.size());
        // System.assertEquals('success', results[0].Status__c);
    }

    @isTest
    public static void testFormIsValid() {

        cont = new PaymentController();
        cont.paymentFirstName = '';
        cont.paymentLastName = '';
        cont.paymentEmail = '';
        cont.paymentPhone = '';
        cont.membershipType = 'Group';
        cont.memberCount = 0;

        Test.startTest();
        Boolean formIsValid = cont.isValidForm();
        Test.stopTest();

        System.assertEquals(false, formIsValid);
        System.assertNotEquals(null, cont.error);
        System.assertNotEquals('', cont.error);
    }

    @isTest
    public static void testProcessPriceChangeGroup() {
        cont = new PaymentController();
        cont.membershipType = 'group';
        cont.memberCount = 5;

        Test.startTest();
        PageReference result = cont.processPriceChange();    
        Test.stopTest();

        System.assertEquals(null, result);
        System.assertNotEquals(null, cont.price);
    }

    @isTest
    public static void testConferenceRoomBooking() {
        setup();
        PageReference currentPage = Page.Payment;
        currentPage.getParameters().put('conferenceRoom','true');
        currentPage.getParameters().put('conferenceDuration','120');
        currentPage.getParameters().put('conferenceStartTime','Mon Sep 16 12:00:00 GMT 2019');
        currentPage.getParameters().put('conferenceLocation', space.Id);
        currentPage.getParameters().put('memberEmail','unit@test.com');
        Test.setCurrentPage(currentPage);

        cont = new PaymentController();
        cont.paymentFirstName = 'test';
        cont.paymentLastName = 'test';
        cont.paymentPhone = 'test';
        cont.memberCompany = 'test';
        cont.memberCity = 'test';
        cont.memberState = 'California';
        cont.discountCode = '';
        cont.codeOfConductValue = true;
        cont.covidPolicyValue = true;

        
        System.assertEquals('unit@test.com', cont.paymentEmail);
        System.assertEquals('DayPass', cont.membershipType);
        System.assertEquals(true, cont.conferenceRoom);
        
        Test.startTest();
        PageReference result = cont.processToken();
        Test.stopTest();

        //Ensure a reservation got made.
        System.assertEquals(1, [SELECT Id FROM Reservation__c].size());

    }

   
}