force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Charge_ID__c.field-meta.xml
<CustomField>
    <fullName>Charge_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Charge ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Invoice_ID__c.field-meta.xml
<CustomField>
    <fullName>Invoice_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeWebhookEndpointTests.cls
@isTest
public class StripeWebhookEndpointTests {
    public static void setup() {
        StripePaymentServiceMock mock = new StripePaymentServiceMock();
        StripePaymentService.instance = mock;
        
        GoogleCalendarServiceMock gCalMock = new GoogleCalendarServiceMock();
        GoogleCalendarService.instance = gCalMock;
    }


    @isTest
    public static void testProcessEventChargeSucceeded() {
        setup();
        String req = '{' +
                     '    "data":{' +
                     '        "object": {' +
                     '            "id": "CHARGE_ID",' +
                     '            "amount": 3000,' +
                     '            "customer": "CUSTOMER_ID",' +
                     '            "invoice": null,' +
                     '            "receipt_url": "http://reciepts.com/test.pdf"' +
                     '        }' +
                     '    },' +
                     '    "type": "charge.succeeded"' +
                     '}';

        RestRequest request = new RestRequest();
        RestResponse resp = new RestResponse();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/stripe';
        request.httpMethod = 'POST';

        request.requestBody = Blob.valueOf(req);

        RestContext.request = request;
        RestContext.response = resp;
        
        Test.startTest();
        StripeWebhookEndpoint.processEvent();
        Test.stopTest();

        List<Payment_Result__c> results = [SELECT Id, Status__c, Charge_ID__c FROM Payment_Result__c];
        
        System.assertEquals(1, results.size());

        Payment_Result__c res = results[0];

        System.assertEquals('success', res.Status__c);
        System.assertEquals('CHARGE_ID', res.Charge_ID__c);
    }

    @isTest
    public static void testProcessEventChargeFailed() {
        setup();
        String req = '{' +
                     '    "data":{' +
                     '        "object": {' +
                     '            "id": "CHARGE_ID",' +
                     '            "amount": 3000,' +
                     '            "customer": "CUSTOMER_ID",' +
                     '            "invoice": null,' +
                     '            "receipt_url": "http://reciepts.com/test.pdf"' +
                     '        }' +
                     '    },' +
                     '    "type": "charge.failed"' +
                     '}';

        RestRequest request = new RestRequest();
        RestResponse resp = new RestResponse();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/stripe';
        request.httpMethod = 'POST';

        request.requestBody = Blob.valueOf(req);

        RestContext.request = request;
        RestContext.response = resp;
        
        Test.startTest();
        StripeWebhookEndpoint.processEvent();
        Test.stopTest();

        List<Payment_Result__c> results = [SELECT Id, Status__c, Charge_ID__c FROM Payment_Result__c];
        
        System.assertEquals(1, results.size());

        Payment_Result__c res = results[0];

        System.assertEquals('failed', res.Status__c);
        System.assertEquals('CHARGE_ID', res.Charge_ID__c);
    }

    @isTest
    public static void testProcessEventInvoiceSucceeded() {
        setup();
        String req = '{' +
                     '    "data" : {' +

                     '        "object": {' +
                     '            "id": "INVOICE_ID",' +
                     '            "charge": "CHARGE_ID",' +
                     '            "customer": "CUSTOMER_ID",' +
                     '            "lines": {' +
                     '                "data": [' +
                     '                    {' +
                     '                        "id": "SUBSCRIPTION_ID"' +
                     '                    }' +
                     '                ]' +
                     '                ' +
                     '            }' +
                     '        }' +
                     '    },' +
                     '    "type" : "invoice.payment_succeeded"' +
                     '}' ;

        RestRequest request = new RestRequest();
        RestResponse resp = new RestResponse();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/stripe';
        request.httpMethod = 'POST';

        request.requestBody = Blob.valueOf(req);

        RestContext.request = request;
        RestContext.response = resp;
        
        Test.startTest();
        StripeWebhookEndpoint.processEvent();
        Test.stopTest();

        List<Payment_Result__c> results = [SELECT Id, Status__c, Invoice_ID__c FROM Payment_Result__c];
        
        System.assertEquals(1, results.size());

        Payment_Result__c res = results[0];

        System.assertEquals('success', res.Status__c);
        System.assertEquals('INVOICE_ID', res.Invoice_ID__c);
    }

    @isTest
    public static void testProcessEventInvoiceFailed() {
        setup();
        String req = '{' +
                     '    "data" : {' +

                     '        "object": {' +
                     '            "id": "INVOICE_ID",' +
                     '            "charge": "CHARGE_ID",' +
                     '            "customer": "CUSTOMER_ID",' +
                     '            "lines": {' +
                     '                "data": [' +
                     '                    {' +
                     '                        "id": "SUBSCRIPTION_ID"' +
                     '                    }' +
                     '                ]' +
                     '                ' +
                     '            }' +
                     '        }' +
                     '    },' +
                     '    "type" : "invoice.payment_failed"' +
                     '}' ;

        RestRequest request = new RestRequest();
        RestResponse resp = new RestResponse();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/stripe';
        request.httpMethod = 'POST';

        request.requestBody = Blob.valueOf(req);

        RestContext.request = request;
        RestContext.response = resp;
        
        Test.startTest();
        StripeWebhookEndpoint.processEvent();
        Test.stopTest();

        List<Payment_Result__c> results = [SELECT Id, Status__c, Invoice_ID__c FROM Payment_Result__c];
        
        System.assertEquals(1, results.size());

        Payment_Result__c res = results[0];

        System.assertEquals('failed', res.Status__c);
        System.assertEquals('INVOICE_ID', res.Invoice_ID__c);
    }



    @isTest
    public static void testProcessEventCouponCreated() {
        setup();
        String req = '{' +
                     '    "data" : {' +
                     '        "object": {' +
                     '            "id" : "TESTCOUPON",' +
                     '            "amount_off": 1000,' +
                     '            "currency":"usd",' +
                     '            "name":"Test Coupon",' +
                     '            "valid":true,' +
                     '            "duration_in_months":6,' +
                     '            "duration":"repeating",' +
                     '            "redeem_by":1569447532,' +
                     '            "max_redemptions":10,' +
                     '            "times_redeemed":0' +
                     '        }' +
                     '    },' +
                     '    "type" : "coupon.created"' +
                     '}';

        RestRequest request = new RestRequest();
        RestResponse resp = new RestResponse();
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/stripe';
        request.httpMethod = 'POST';

        request.requestBody = Blob.valueOf(req);

        RestContext.request = request;
        RestContext.response = resp;
        
        Test.startTest();
        StripeWebhookEndpoint.processEvent();
        Test.stopTest();

        List<Discount__c> discounts = [SELECT Id FROM Discount__c];

        System.assertNotEquals(0, discounts.size());
    }
}