force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount_Off__c.field-meta.xml
<CustomField>
    <fullName>Amount_Off__c</fullName>
    <label>Amount Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forever</fullName>
                <default>true</default>
                <label>Forever</label>
            </value>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Repeating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Gift_Membership__c.field-meta.xml
<CustomField>
    <fullName>Gift_Membership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gift Membership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Purchaser_Email__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Purchaser Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Times_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Times_Redeemed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Valid__c.field-meta.xml
<CustomField>
    <fullName>Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Stripe Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RedeemGiftTests.cls
@isTest
public with sharing class RedeemGiftTests {
    static RedeemGiftController cont;

    public static void setup(Integer option) {
        StripePaymentServiceMock mock = new StripePaymentServiceMock();
        StripePaymentService.instance = mock;
        
        cont = new RedeemGiftController();
        if(option == 1)
        {
            cont.memberFirstName = 'Unit';
            cont.memberLastName = 'Test 1';
            cont.memberEmail = 'unit@test.com';
            cont.memberPhone = '1235551234';
            cont.memberCompany = 'Unit Tests R Us';
            cont.memberCount = 1;
            cont.memberCity = 'Townsville';
            cont.memberState = 'California';
            cont.discountCode = 'GO';
            cont.checkboxValue = true;
        }
        if(option == 2)
        {
            cont.memberFirstName = '';
            cont.memberLastName = '';
            cont.memberEmail = '';
            cont.memberPhone = '';
            cont.memberCompany = '';
            cont.memberCity = '';
            cont.memberState = '';
            cont.discountCode = '';
            cont.checkboxValue = false;
        }
    }

    @isTest
    public static void validForm(){
        Boolean checkValid;
        setup(2);
        checkValid = cont.formIsValid();
        System.assertEquals(false, checkValid);
        
        setup(1);
         checkValid = cont.formIsValid();
         System.assertEquals(true, checkValid);
    }
    @isTest
    public static void AandC() {
        setup(1);
        
        cont.pullAccountAndContact();
        System.AssertEquals('unit@test.com',cont.contact.Email);
        
       
    }
    @isTest
    public static void AandC2(){
        
        setup(1);  
        Account act = new Account(Name = 'Unit Tests R Us');
        upsert act;
        act = [SELECT Id, Name FROM Account WHERE Name = 'Unit Tests R Us'];
        System.AssertEquals('Unit Tests R Us',act.Name);
        Contact con = new Contact(FirstName = 'Unit', LastName = 'Test 1', Account = act, Email = 'unit@test.com', Phone = '1235551234');
        upsert con;
        cont.pullAccountAndContact();
        System.AssertEquals('Unit Tests R Us',cont.account.Name);
    }
    @isTest
    public static void testMemberNew() {
        setup(1);
        Discount__c discount = new Discount__c(Name = 'GO',Code__c = 'GO',Times_Redeemed__c = 0, Max_Redemptions__c = 1,Amount_Off__c = 0, 	Duration__c = 'Forever',  Gift_Membership__c = true, Purchaser_Email__c = 'test@test.com', Valid__c = True);
        insert discount;
        Test.startTest();
        cont.processForm();
        Test.stopTest();
    
            
        List<Contact> conts = [SELECT Id, AccountId, Cowork_Stripe_Customer_Id__c FROM Contact];
        System.assertEquals(1, conts.size());
 
        List<Account> accts = [SELECT Id FROM Account];
        System.assertEquals(1, accts.size());

        System.assertEquals(accts[0].Id, conts[0].AccountId, 'The created Contact does not link to the created account.');

        List<Membership__c> memberships = [SELECT Id, Stripe_Subscription_Id__c FROM Membership__c];
        System.assertEquals(1, memberships.size());
        
        cont.processForm();
		 System.assertEquals('This discount code has already been redeemed.', cont.error);
        
        discount = new Discount__c(Name = 'GO2',Code__c = 'GO2',Times_Redeemed__c = 0, Max_Redemptions__c = 1,Amount_Off__c = 0, Gift_Membership__c = true, Purchaser_Email__c = 'test@test.com', Duration__c = 'Forever', Valid__c = True);
        insert discount;
        cont.discountCode = 'GO2';
        
         cont.processForm();
		 System.assertEquals('There is already an active membership under that email address.', cont.error);
        
        cont.memberEmail= 'tester2@test.com';
        cont.discountCode = 'GO3';
        
        discount = new Discount__c(Name = 'GO3',Code__c = 'GO3', Max_Redemptions__c = 1,Amount_Off__c = 0, 	Duration__c = 'Forever', Gift_Membership__c = true, Purchaser_Email__c = 'test@test.com', Valid__c = True);
        insert discount;
         cont.memberLastName = 'Test 10';
         cont.memberEmail = 'unit10@test.com';
         cont.memberPhone = '101 010 1010';
        cont.processForm();
        
        discount = [SELECT Name, Times_Redeemed__c FROM Discount__c WHERE Code__c= 'GO3'];        
        System.assertEquals(1, discount.Times_Redeemed__c);
    }
    @isTest
    public static void BadInput() {
        setup(2);
        PageReference result;
        Discount__c discount = new Discount__c(Name = 'GO',Code__c = 'GO',Times_Redeemed__c = 0, Max_Redemptions__c = 1,Amount_Off__c = 0, 	Duration__c = 'Forever', Gift_Membership__c = true,Purchaser_Email__c = 'test@test.com', Valid__c = True);
        insert discount;
        Test.startTest();
        result = cont.processForm();
        Test.stopTest();
    
        System.assertEquals(null, result);  
    }
    
    @isTest
    public static void BadCode() {
        setup(1);
        cont.discountCode = '2';
        cont.processForm();
       
    
        System.assertEquals('That is an invalid Gift code.', cont.error);  
    }
    
}