force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount_Off__c.field-meta.xml
<CustomField>
    <fullName>Amount_Off__c</fullName>
    <label>Amount Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forever</fullName>
                <default>true</default>
                <label>Forever</label>
            </value>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Repeating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Months__c</fullName>
    <label>Duration In Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Gateway__c.field-meta.xml
<CustomField>
    <fullName>Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gateway</label>
    <referenceTo>Gateway__c</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Redeem_By__c.field-meta.xml
<CustomField>
    <fullName>Redeem_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Redeem By</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Times_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Times_Redeemed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Valid__c.field-meta.xml
<CustomField>
    <fullName>Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Charge_ID__c.field-meta.xml
<CustomField>
    <fullName>Charge_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Charge ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>The ID of the Stripe Customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Gateway__c.field-meta.xml
<CustomField>
    <fullName>Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gateway</label>
    <referenceTo>Gateway__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Invoice_ID__c.field-meta.xml
<CustomField>
    <fullName>Invoice_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>The ID of the Subscription in Stripe.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeWebhookEndpoint.cls
@RestResource(urlMapping='/stripe')
global class StripeWebhookEndpoint {
    
    //POST Request
    @HttpPost
    global static void processEvent() {
        Map<String, Object> response = (Map<String, Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        String event = (String)response.get('type');

        if (event.startsWith('charge')) {
            processCharge(response);
        } else if (event.startsWith('invoice')) {
            processInvoice(response);
        } else if (event.startsWith('coupon')) {
            processCoupon(response);
        }

        RestContext.response.statusCode = 200;
    }

    private static void processCharge(Map<String, Object> data) {
        system.debug('processing processCharge');

        Map<String, Object> dataObj = (Map<String,Object>)((Map<String, Object>)data.get('data')).get('object');

        String chargeId = (String)dataObj.get('id');
        Decimal amount = ((Decimal)dataObj.get('amount'))/100; //Stripe stores money in the smallest denomination (cents)
        String customerId = (String)dataObj.get('customer');
        String invoiceId = (String)dataObj.get('invoice');
        String receiptUrl = (String)dataObj.get('receipt_url');

        String status;
        if ((String)data.get('type') == 'charge.succeeded') {
            status = 'success';
        } else {
            status = 'failed';
        }

        Payment_Result__c result = new Payment_Result__c(
            Charge_ID__c = chargeId,
            Customer_ID__c = customerId,
            Invoice_ID__c = invoiceId,
            Status__c = status,
            Receipt_URL__c = receiptUrl,
            Amount__c = amount,
            Source__c = 'Stripe Charge/Invoice',
            Gateway__c = getGatewayId()
        );

        PaymentResultProcessingService.upsertPaymentResult(result);

    }

    private static void processInvoice(Map<String, Object> data) {
        system.debug('processing processInvoice');

        //Pull the Object Data out of the event.
        Map<String, Object> dataObj = (Map<String,Object>)((Map<String, Object>)data.get('data')).get('object');

        //Get the invoiceId from the dataObj.
        String invoiceId = (String)dataObj.get('id');
        String customerId = (String)dataObj.get('customer');
        String chargeId = (String)dataObj.get('charge');

        //Get the subscription.
        String subscriptionId;
        try {
            subscriptionId = (String)((Map<String,Object>)((List<Object>)((Map<String, Object>)dataObj.get('lines')).get('data'))[0]).get('id');
        } catch(Exception ex) {
            subscriptionId = null;
        }

        String status;

        if ((String)data.get('type') == 'invoice.payment_succeeded') {
            status = 'success';
        } else {
            status = 'failed';
        }

        Payment_Result__c result = new Payment_Result__c(
            Charge_ID__c = chargeId,
            Customer_ID__c = customerId,
            Invoice_ID__c = invoiceId,
            Subscription_ID__c = subscriptionId,
            Status__c = status,
            Source__c = 'Stripe Charge/Invoice',
            Gateway__c = getGatewayId()
        );

        PaymentResultProcessingService.upsertPaymentResult(result);
    }

    private static void processCoupon(Map<String, Object> data) {
        Map<String, Object> dataObj = (Map<String,Object>)((Map<String, Object>)data.get('data')).get('object');

        String name = (String)dataObj.get('name');
        String code = (String)dataObj.get('id');
        Boolean valid = (Boolean)dataObj.get('valid');
        Integer amount_off = (Integer)dataObj.get('amount_off');
        Integer duration_in_months = (Integer)dataObj.get('duration_in_months');
        String duration = (String)dataObj.get('duration');

        Datetime redeem_by;
        if (dataObj.containsKey('redeem_by') && dataObj.get('redeem_by') != null) {
            redeem_by = Datetime.newInstance((Long)dataObj.get('redeem_by')*1000);
        }

        Integer times_redeemed = (Integer)dataObj.get('times_redeemed');
        Integer max_redemptions = (Integer)dataObj.get('max_redemptions');

        Discount__c record = new Discount__c();

        List<Discount__c> existing = [SELECT Id, Name, Code__c, Valid__c, Amount_Off__c  FROM Discount__c WHERE Code__c = :code];

        if (existing.size() > 0) {
            record = existing[0];
        } else {
            record = new Discount__c();
        }

        String type = (String)data.get('type');
        if (type == 'coupon.created') {
            
        } else if (type == 'coupon.updated' || type == 'coupon.deleted') {
           
            if (type=='coupon.deleted') {
                delete record;
                return;
            }
        }

        record.Name = name;
        record.Code__c = code;
        record.Valid__c = valid;
        if(amount_off != null) {
            record.Amount_Off__c = amount_off/100;
        }

        if (dataObj.containsKey('redeem_by')) {
            record.Redeem_By__c = redeem_by;
        }

        record.Gateway__c = getGatewayId();
        record.Times_Redeemed__c = times_redeemed;
        record.Duration__c = duration;
        record.Max_Redemptions__c = max_redemptions;
        record.Duration_In_Months__c = duration_in_months;

        upsert record;
    }

    public static Id getGatewayId() {
        Map<String, String> params = RestContext.request.params;
        if (params.containsKey('gateway')) {
            String department = params.get('gateway');
            Gateway__c gateway = CredentialService.getStripeGateway(department);
            return gateway.Id;
        } else {
            return null;
        }
    }

}