force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount_Off__c.field-meta.xml
<CustomField>
    <fullName>Amount_Off__c</fullName>
    <label>Amount Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forever</fullName>
                <default>true</default>
                <label>Forever</label>
            </value>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Repeating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DiscountTriggerTests.cls
@isTest 
public class DiscountTriggerTests {
    public static void setup() {
        StripePaymentService.instance = new StripePaymentServiceMock();
    }

    @isTest
    public static void testInsert() {
        setup();
        
        Discount__c discount = new Discount__c(Duration__c = 'Once', Amount_Off__c = 349, Code__c = 'Discount1234');

        Test.startTest();
        insert discount;
        Test.stopTest();

        System.assertNotEquals(null, discount);
    }

    @isTest
    public static void testDelete() {
        setup();
        
        Discount__c discount = new Discount__c(Duration__c = 'Once', Amount_Off__c = 349, Code__c = 'Discount1234');
        insert discount;

        Test.startTest();
        delete discount;
        Test.stopTest();

        System.assertEquals(0, [SELECT Id FROM Discount__c].size());
    }
}