force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Amount_Off__c.field-meta.xml
<CustomField>
    <fullName>Amount_Off__c</fullName>
    <label>Amount Off</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Forever</fullName>
                <default>true</default>
                <label>Forever</label>
            </value>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Repeating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Duration_In_Months__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Months__c</fullName>
    <label>Duration In Months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Redeem_By__c.field-meta.xml
<CustomField>
    <fullName>Redeem_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Redeem By</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/StripeDiscountUpdateBatch.cls
public class StripeDiscountUpdateBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    public Set<Id> discountIds;
    public string mode;

    public static String department = 'Cowork';

    public Database.QueryLocator start(Database.BatchableContext BC) {
        System.assertNotEquals(null, discountIds, 'discountIds in StripeDiscountUpdateBatch is null.');

        String query = 'SELECT Code__c, Amount_Off__c, Name, Duration_In_Months__c, Duration__c, Redeem_By__c, Max_Redemptions__c, Id FROM Discount__c WHERE Id IN :discountIds';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Discount__c> discounts) {
        for (Discount__c d : discounts) {
            // if (mode == 'update') {
            //     StripePaymentService.getInstance().updateDiscount(d);
            /*} else*/ if (mode == 'insert') {
                StripePaymentService.getInstance().createDiscount(department, d);
            } else if (mode == 'delete') {
                StripePaymentService.getInstance().deleteDiscount(department, d);
            }
        }
    }

    public void finish(Database.BatchableContext BC) {}
}