force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <description>Created By: Dylan Bowman (RC) 
Department: Stripe
Purpose: Storing coupon data from Stripe</description>
    <label>Discount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Gift_Membership__c.field-meta.xml
<CustomField>
    <fullName>Gift_Membership__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Gift Membership</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Max_Redemptions__c.field-meta.xml
<CustomField>
    <fullName>Max_Redemptions__c</fullName>
    <label>Max Redemptions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recipient_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recipient First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recipient_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Recipient Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Times_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Times_Redeemed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Valid__c.field-meta.xml
<CustomField>
    <fullName>Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Membership_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Start_Date__c</fullName>
    <description>CC Hashtag Membership Start Date Visualforce</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Number_of_Members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Members__c</fullName>
    <defaultValue>1</defaultValue>
    <description>CC Hashtag Allow for a number of members to be entered Manual/Auto</description>
    <inlineHelpText>Defaults to one unless another value is entered.</inlineHelpText>
    <label>Number of Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Day Pass</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant</fullName>
            </value>
            <value>
                <fullName>Hashtag + Lift</fullName>
            </value>
            <value>
                <fullName>Individual Yearly</fullName>
            </value>
            <value>
                <fullName>Student Yearly</fullName>
            </value>
            <value>
                <fullName>Virtual Tenant + Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>SV-{000000}</displayFormat>
        <label>Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Created By: AF
Business Unit: Executive Reporting
Purpose: Denotes which contact completed the survey
Populated: Auto via survey / manual</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>GS
Purpose: WFT Survey</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>US_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: RS
For: Survey flow</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Resent</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RedeemGiftController.cls
public with sharing class RedeemGiftController {
    public string error{get;set;} 

    public String memberFirstName {get;set;}
    public String memberLastName {get;set;}
    public String memberEmail {get;set;}
    public String memberPhone {get;set;}
    public String memberCompany {get;set;}
    public String memberCity {get;set;}
    public String memberState {get;set;}
    public String membershipType {get;set;}
    public Integer memberCount {get;set;}
    public String discountCode{get;set;}
    public Boolean checkboxValue{get; set;}

    public Membership__c membership;
    public Contact contact;
    public Account account;

    List<String> states = new List<String>();
    public List<SelectOption> getPopulateStates() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','State'));
        for (Schema.PicklistEntry pe : SObjectType.Survey__c.fields.State__c.getPicklistValues()) {
            options.add(new SelectOption(pe.getLabel(), pe.getLabel()));
        }   
        return options;
    }
        
    public List<String> getStates() {
        return states;
    }
        
    public void setStates(List<String> countries) {
        this.states = states;
    }

    public RedeemGiftController() {

        membershipType = 'Individual Yearly';
        System.debug(membershipType);

    }
    


    public PageReference processForm() {
        
        error = '';
       
        System.debug('Get in processForm');

        PageReference result = null; 

        //Clean the data of whitespace. 
        memberFirstName = memberFirstName.trim();
        memberLastName = memberLastName.trim();
        memberEmail = memberEmail.trim();
        memberPhone = memberPhone.trim();
        memberCompany = memberCompany.trim();
        memberCity = memberCity.trim();
        if (!String.isBlank(memberState)) {
            memberState = memberState.trim();
        }
        discountCode = discountCode.trim();

        if (!formIsValid()) {
            System.debug('Form is invalid');
            return result;
        }
        //If there's a discount code applied, make sure it's valid. If not, yell at the user.
        Discount__c discountRecord = null;

        if (discountCode != '') {
            List<Discount__c> codes = [SELECT Id, Code__c, Times_Redeemed__c, Max_Redemptions__c FROM Discount__c WHERE Code__c = :discountCode AND Valid__c = true AND Gift_Membership__c = true];

            if (codes.size() == 0) {
                System.debug('Invalid Discount Code');
                error = 'That is an invalid Gift code.';
                return result;
            } else {
                discountRecord = codes[0];
                if(discountRecord.Times_Redeemed__c >= discountRecord.Max_Redemptions__c ) {
                    System.debug('Invalid Discount Code');
                    error = 'This discount code has already been redeemed.';
                    return result;
                }
            }
        }

        System.debug(discountRecord);
        
        //Search for the Account and Contact, trying to match based on what the user entered.
        pullAccountAndContact();

        //See if there's an active membership for the Contact. If there is, yell at the user.
        if ([SELECT Id FROM Membership__c WHERE Status__c = 'Active' AND Contact__c = :contact.Id].size() > 0) {
            System.debug('Active membership already exists');
            error = 'There is already an active membership under that email address.';
            return result;
        }

        memberCount = 1;

        //Create a membership for the user.
        membership = new Membership__c(Contact__c = contact.Id,
                                       Membership_Start_Date__c = Date.today(),
                                       Status__c = 'Active',
                                       Type__c = membershipType,
                                       Number_Of_Members__c = memberCount);

        result = new PageReference('https://hashtagcoworkplace.com/membership-redeemed/');
            
           


        //If it's a new account, insert the account.
        if (account.Id == null) {
            //Balaji
            system.debug(account);
            insert account;
        }

        contact.AccountId = account.Id;
        upsert contact;

        membership.Contact__c = contact.Id;
      

        insert membership;

       System.debug(membership);

        //Update the discount, if there is one.
        if (discountRecord != null) {
            if(discountRecord.Times_Redeemed__c == null){
                discountRecord.Times_Redeemed__c = 1;
            }
            else {
                discountRecord.Times_Redeemed__c += 1;
            }
            discountRecord.Recipient_First_Name__c = contact.FirstName;
            discountRecord.Recipient_Last_Name__c = contact.LastName;
            update discountRecord;
        }

        System.debug(discountRecord);
        System.debug(result);
        return result;
    }

   

    public Boolean formIsValid() {
        List<String> errors = new List<String>();
        System.debug('In Form is Valid');
        if (memberFirstName == '') {
            errors.add('First Name must be filled in.');
        }
        if (memberLastName == '') {
            errors.add('Last Name must be filled in.');
        }
        if (memberEmail == '') {
            errors.add('Email must be filled in.');
        }
        if (memberPhone == '') {
            errors.add('Phone must be filled in.');
        }

        if(discountCode == ''){
            errors.add('You must have a Gift Code to redeem a gift.');
        }

        if (checkboxValue == false) {
            errors.add('You must agree to the code of conduct.');
        }

        if (!String.isBlank(memberCity) && String.isBlank(memberState)) {
            errors.add('Please select a state.');
        }

        if (errors.size() > 0) {
            error = String.join(errors, '\n');
            return false;
        }

        return true;
    }

    public void pullAccountAndContact() {
        //Look for an existing Contact/Account.
        List<Contact> conts = [SELECT Id, FirstName, LastName, Email, Phone, AccountId FROM Contact WHERE Email LIKE :memberEmail];
        contact = new Contact();

        if (conts.size() > 0) {
            contact = conts[0];
        }

        List<Account> accts;

        if (contact.AccountId != null) {
            accts = [SELECT Id FROM Account WHERE Id = :contact.AccountId];
        } else if (memberCompany != '') {
            accts = [SELECT Id FROM Account WHERE Name LIKE :memberCompany AND BillingCity LIKE :memberCity AND BillingState LIKE :memberState];
        } else {
            accts = [SELECT Id FROM Account WHERE RecordType.Name = 'Individuals'];
        }

        if (accts.size() > 0) {
            account = accts[0];
        } else {
            account = new Account(Name = memberCompany, BillingCity = memberCity, BillingState = memberState);
        }

        if(contact.Id == null) {
            contact = new Contact();
            contact.FirstName = memberFirstName;
            contact.LastName = memberLastName;
            contact.Email = memberEmail;
            contact.Phone = memberPhone;
            if (account.Id != null) {
                contact.AccountId = account.Id;
            }
        }
    }

}