force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gateway__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cowork</fullName>
            </value>
            <value>
                <fullName>WFT</fullName>
            </value>
            <value>
                <fullName>Shift3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gateway__c/fields/Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Publishable_Key__c</fullName>
    <label>Publishable Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Gateway__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/CredentialServiceTests.cls
@isTest
public class CredentialServiceTests {
    static Gateway__c gateway;
    
    public static void setup() {
        gateway= new Gateway__c(
            Publishable_Key__c = 'Public',
            Secret_Key__c = 'Secret',
            Department__c = 'Cowork',
            Active__c = true
        );
        insert gateway;
    }

    @isTest
    public static void testGetStripeSettings() {
        setup();
        
        Test.startTest();
        Gateway__c settings = CredentialService.getStripeGateway('Cowork');
        Test.stopTest();

        System.assertNotEquals(null, settings);
        System.assertEquals(gateway.Id, settings.Id);
    }

    @isTest
    public static void testGetPublicStripeKey() {
        setup();
        
        Test.startTest();
        String key = CredentialService.getPublicStripeKey('Cowork');
        Test.stopTest();

        System.assertEquals('Public', key);
    }

    @isTest
    public static void testGetPrivateStripeKey() {
        setup();
        
        Test.startTest();
        String key = CredentialService.getPrivateStripeKey('Cowork');
        Test.stopTest();

        System.assertEquals('Secret', key);
    }
}