force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gateway__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cowork</fullName>
            </value>
            <value>
                <fullName>WFT</fullName>
            </value>
            <value>
                <fullName>Shift3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SandboxInitialization.cls
public class SandboxInitialization implements SandboxPostCopy{
    public void runApexClass(SandboxContext context) {
        System.debug('Org ID: ' + context.organizationId());
        System.debug('Sandbox ID: ' + context.sandboxId());
        System.debug('Sandbox Name: ' + context.sandboxName());
        System.debug('Profile of User: ' + userinfo.getProfileId());
        System.debug('User Name: ' + userinfo.getName());
        System.debug('User Type: ' + userinfo.getUserType());
        System.debug('User Id: ' + userinfo.getUserId());

        Id individualAcctRtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId();

        List<Account> existingAccts = [SELECT Id FROM Account WHERE RecordTypeId = :individualAcctRtId];

        if (existingAccts.size() == 0) {
            Account acct = new Account(
                Name = 'Individuals',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individuals').getRecordTypeId()
            );

            insert acct;
        }
     
        Gateway__c coworkGateway = new Gateway__c(
            Name = 'Cowork (Test)',
            Department__c = 'Cowork',
            Active__c = true
        );

        
        Gateway__c wftGateway = new Gateway__c(
            Name = 'WFT (Test)',
            Department__c = 'WFT',
            Active__c = true
        );

        insert new List<Gateway__c>{coworkGateway, wftGateway};
    }
}