force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Result__c/Payment_Result__c.object-meta.xml
<CustomObject>
    <description>Created by: Dylan Bowman (RC)
Business Unit: All (Payment Processing)
Purpose: To track payments via Stripe.</description>
    <label>Payment Result</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Payment Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Result__c/fields/Charge_ID__c.field-meta.xml
<CustomField>
    <fullName>Charge_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Charge ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <description>The ID of the Stripe Customer.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Gateway__c.field-meta.xml
<CustomField>
    <fullName>Gateway__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gateway</label>
    <referenceTo>Gateway__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Invoice_ID__c.field-meta.xml
<CustomField>
    <fullName>Invoice_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Receipt_URL__c.field-meta.xml
<CustomField>
    <fullName>Receipt_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Receipt URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created By: CC
Department: WFT
Purpose: Connect Registration to Payments</description>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Payment Results</relationshipLabel>
    <relationshipName>Payment_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Result__c/fields/Subscription_ID__c.field-meta.xml
<CustomField>
    <fullName>Subscription_ID__c</fullName>
    <description>The ID of the Subscription in Stripe.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Subscription ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Displays the status of a student&apos;s Registration
Populated: Auto with Formula</description>
    <formula>IF( AND( Dropped__c = false, Dropped_w_Credit__c = false),
    IF( AND( Class__r.Start_Date__c &lt;= TODAY(), Class__r.End_Date__c &gt; TODAY() ), &apos;In Progress&apos;,
        IF( Class__r.End_Date__c &lt;= TODAY(), &apos;Completed&apos;, &apos;Registered&apos; )
      ),
    IF( Dropped__c = true, &apos;Dropped&apos;, &apos;Dropped w/Credit&apos;)
  )</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentResultProcessingService.cls
public class PaymentResultProcessingService {

    public static Payment_Result__c upsertPaymentResult(Payment_Result__c input) {
        //If we're updating an existing Payment Result.
        Payment_Result__c existing;
        if (input.Id != null) {
            existing = [SELECT Id, Amount__c, Charge_ID__c, Contact__c, Customer_ID__c, Gateway__c, Invoice_ID__c, Receipt_URL__c, Membership__c, Status__c, Subscription_ID__c FROM Payment_Result__c WHERE Id = :input.Id];
        } else if (input.Charge_ID__c != null) {
            List<Payment_Result__c> existingList = [SELECT Id, Amount__c, Charge_ID__c, Contact__c, Customer_ID__c, Gateway__c, Invoice_ID__c, Receipt_URL__c, Membership__c, Status__c, Subscription_ID__c FROM Payment_Result__c WHERE Charge_ID__c = :input.Charge_ID__c];

            if (existingList.size() > 0) {
                existing = existingList[0];
            } else {
                insert input;
                return input;
            }
        } else {
            //There isn't a payment result that matches, so insert and return.
            insert input;
            return input;
        }
        //Copy over every field from input if there is one.
        if (input.Amount__c != null) {
            existing.Amount__c = input.Amount__c;
        }

        if (input.Gateway__c != null) {
            existing.Gateway__c = input.Gateway__c;
        }

        if (input.Charge_ID__c != null) {
            existing.Charge_ID__c = input.Charge_ID__c;
        }

        if (input.Contact__c != null) {
            existing.Contact__c = input.Contact__c;
        }

        if (input.Customer_ID__c != null) {
            existing.Customer_ID__c = input.Customer_ID__c;
        }

        if (input.Invoice_ID__c != null) {
            existing.Invoice_ID__c = input.Invoice_ID__c;
        }

        if (input.Membership__c != null) {
            existing.Membership__c = input.Membership__c;
        }

        if (input.Receipt_URL__c != null) {
            existing.Receipt_URL__c = input.Receipt_URL__c;
        }

        if (input.Status__c != null) {
            existing.Status__c = input.Status__c;
        }

        if (input.Subscription_ID__c != null) {
            existing.Subscription_ID__c = input.Subscription_ID__c;
        }

        if (input.Registration__c != null) {
            existing.Registration__c = input.Registration__c;
        }

        update existing;
        return existing;
    }

}