force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gateway__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cowork</fullName>
            </value>
            <value>
                <fullName>WFT</fullName>
            </value>
            <value>
                <fullName>Shift3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gateway__c/fields/Publishable_Key__c.field-meta.xml
<CustomField>
    <fullName>Publishable_Key__c</fullName>
    <label>Publishable Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Gateway__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Stripe_Settings__c/Stripe_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Stripe Settings</label>
</CustomObject>

force-app/main/default/objects/Stripe_Settings__c/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Public Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CredentialService.cls
public class CredentialService {
    static Map<String, Gateway__c> records;
    public static Gateway__c getStripeGateway(String department) {
        if (records == null) {
            getRecords();
        }
        return records.get(department);
    }

    public static string getPublicStripeKey(String department) {
        return getStripeGateway(department).Publishable_Key__c;
    }

    public static string getPrivateStripeKey(String department) {
        return getStripeGateway(department).Secret_Key__c;
    }

    private static  void getRecords() {
        List<Gateway__c> gateways = [SELECT Id, Department__c, Publishable_Key__c, Secret_Key__c FROM Gateway__c WHERE Active__c = true];
        records = new Map<String, Gateway__c>();

        for (Gateway__c gateway : gateways) {
            records.put(gateway.Department__c, gateway);
        }
    }


    // private static Stripe_Settings__c settings;

    // public static Stripe_Settings__c getStripeSettings() {
    //     if (settings == null) {
    //         settings = Stripe_Settings__c.getInstance();
    //     }

    //     return settings;
    // }

    // public static string getPublicStripeKey() {
    //     return getStripeSettings().Public_Key__c;
    // }

    // public static string getPrivateStripeKey() {
    //     return getStripeSettings().Secret_Key__c;
    // }
}