force-app/main/default/objects/Apprentice__c/Apprentice__c.object-meta.xml
<CustomObject>
    <label>Apprentice</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Apprentice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apprentices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Apprenticeship</label>
    <referenceTo>Apprenticeship__c</referenceTo>
    <relationshipLabel>Apprentices</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/Apprenticeship__c.object-meta.xml
<CustomObject>
    <label>Apprenticeship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Apprenticeship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apprenticeships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Classes</description>
    <label>Class</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Select class type for use in other processes
Populated: Auto via Web form</description>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Websites for Beginners</fullName>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites</fullName>
            </value>
            <value>
                <fullName>Javascript for Beginners</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II)</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part I of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part I of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Intro to Angular2 (Part II of II) (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Intro to Angular2 (Part II of II) (Virtual Class)</label>
            </value>
            <value>
                <fullName>Javascript for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Javascript for Beginners (Virtual Class)</label>
            </value>
            <value>
                <fullName>Mobile-Friendly Websites (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Mobile-Friendly Websites (Virtual Class)</label>
            </value>
            <value>
                <fullName>React (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>React (Virtual Class)</label>
            </value>
            <value>
                <fullName>Websites for Beginners (Virtual Class)</fullName>
                <isActive>false</isActive>
                <label>Websites for Beginners (Virtual Class)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Gateway__c/Gateway__c.object-meta.xml
<CustomObject>
    <description>Created by: DB (Rogue Cloud)
For: Stripe Integration
Function: To store API Keys for Stripe.
Populated By: Admin.</description>
    <label>Gateway</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Class Registrations</description>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Created By: AF
Business Unit: Geekwise Users
Purpose: Link a Class to the Registration record
Populated: Manual/Auto via Web form</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactoryTest.cls
@isTest
public class TestDataFactoryTest{
    @isTest static void testCreateContact(){
        List<Contact> contacts = new List<Contact>();
        contacts.add(TestDataFactory.createContact());
        insert contacts;
        List<Contact> contactsDB = [SELECT Id FROM Contact];
        System.assertEquals(1,contactsDB.size());
    }

    @isTest static void testcreateMultipleContacts(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
        List<Contact> contacts = TestDataFactory.createMultipleContacts(10, acc);
        insert contacts;
        List<Contact> contactsDB = [SELECT Id FROM Contact];
        System.assertEquals(10, contactsDB.size());
    }

    @isTest static void testCreateLead(){
        List<Lead> leads = new List<Lead>();
        leads.add(TestDataFactory.createLead());
        insert leads;
        List<lead> LeadsDB = [SELECT Id FROM Lead];
        System.assertEquals(1, leadsDB.size());
    }

    @isTest static void testCreateLeadWithRecordType(){
        List<Lead> leads = new List<Lead>();
        leads.add(TestDataFactory.createLead('BWRD'));
        insert leads;
        List<lead> LeadsDB = [SELECT Id FROM Lead];
        System.assertEquals(1, leadsDB.size());
    }

    @isTest static void testCreateLeadWithInvalidRecordType(){
        List<Lead> leads = new List<Lead>();
        Lead lead =  TestDataFactory.createLead('BWRDX');
        if (lead != null) leads.add(lead);
        if (leads.size() > 0) insert leads;
        List<lead> LeadsDB = [SELECT Id FROM Lead];
        System.assertEquals(0, leadsDB.size());
    }    

    @isTest static void testCreateMultipleLeadsWithRecordType(){
        List<Lead> leads = TestDataFactory.createMultipleLeads(50, 'BWRD');
        insert leads;
        List<lead> LeadsDB = [SELECT Id FROM Lead];
        System.assertEquals(50, leadsDB.size());
    }

    @isTest static void testCreateMultipleLeadsWithoutRecordType(){
        List<Lead> leads = TestDataFactory.createMultipleLeads(25, '');
        insert leads;
        List<lead> LeadsDB = [SELECT Id FROM Lead];
        System.assertEquals(25, leadsDB.size());
    }

    @isTest static void testCreateCase(){
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        List<Case> cases = new List<Case>();
        Cases.add(TestDataFactory.createCase(con1));
        insert Cases;
        List<Case> CasesDB = [SELECT Id FROM Case];
        System.assertEquals(1, CasesDB.size());
    }

    @isTest static void testCreateCaseWithRecordType(){
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        List<Case> cases = new List<Case>();
        Cases.add(TestDataFactory.createCase(con1, 'IT'));
        insert Cases;
        List<Case> CasesDB = [SELECT Id FROM Case];
        System.assertEquals(1 ,CasesDB.size());
    }
    @isTest static void testCreateCaseWithInvalidRecordType(){
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        List<Case> cases = new List<Case>();
        Case c =  TestDataFactory.createCase(con1,'ITX');
        if (c != null) cases.add(c);
        if (cases.size() > 0) insert cases;
        List<Case> CasesDB = [SELECT Id FROM Case];
        System.assertEquals(0, casesDB.size());
    }

    @isTest static void testCreateMultipleCasesWithRecordType(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
        List<Case> cases = TestDataFactory.createMultipleCases(15, 'IT', acc);
        List<case> CasesDB = [SELECT Id FROM Case];
        System.assertEquals(15,casesDB.size());
    }

    @isTest static void testCreateMultipleCasesWithOutRecordType(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
        List<Case> cases = TestDataFactory.createMultipleCases(20, '', acc);
        List<case> CasesDB = [SELECT Id FROM Case];
        System.assertEquals(20, casesDB.size());
    }

    @isTest static void testCreateClass(){
        List<Class__c> classes  = new List<Class__c>();
        classes.add(TestDataFactory.createClass('Websites for Beginners'));
        insert classes;
        List<Class__c> classesDB = [SELECT Id FROM Class__c];
        System.assertEquals(1, classesDB.size());
    }

    @isTest static void testCreateClassRound(){
        List<Class__c> classes = TestDataFactory.createClassRound('In-Person','Fresno');
        insert classes;
        List<Class__c> classesDB = [SELECT Id FROM Class__c];
        System.assertEquals(4, classesDB.size());
    }

    @isTest static void testCreateRegistration(){
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        Class__c cls1 = TestDataFactory.createClass('Websites for Beginners');
        insert cls1;
        
        List<Registration__c> regs  = new List<Registration__c>();
        regs.add(TestDataFactory.createRegistration(con1,cls1));
        insert regs;
        List<Registration__c> regsDB = [SELECT Id FROM Registration__c];
        System.assertEquals(1, regsDB.size());
    }

    //TODO CHECK
    @isTest static void testaddRegistrationsToClass(){
        //Make sure and account with Individuals record type is created.
        Account indAccount = TestDataFactory.createIndividualAccount();
        insert indAccount;
        Class__c cls1 = TestDataFactory.createClass('Websites for Beginners');
        insert cls1;
        List<Registration__c> regs = TestDataFactory.addRegistrationsToClass(10, cls1);
        List<Registration__c> regsDB = [SELECT Id FROM Registration__c];
        System.assertEquals(10, regsDB.size());
    }

    @isTest static void testCreateApprenticeship(){
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        
        List<Apprenticeship__c> apss  = new List<Apprenticeship__c>();
        apss.add(TestDataFactory.createApprenticeship(con1));
        insert apss;
        List<Apprenticeship__c> apssDB = [SELECT Id FROM Apprenticeship__c];
        System.assertEquals(1, apssDB.size());
    }

    @isTest static void testCreateApprentice(){
        Contact conLead = TestDataFactory.createContact();
        insert conLead;
        Apprenticeship__c aps1 = TestDataFactory.createApprenticeship(conLead);
        insert aps1;
        Contact con1 = TestDataFactory.createContact();
        insert con1;
        
        List<Apprentice__c> apcs  = new List<Apprentice__c>();
        apcs.add(TestDataFactory.createApprentice(con1,aps1));
        insert apcs;
        List<Apprentice__c> apcsDB = [SELECT Id FROM Apprentice__c];
        System.assertEquals(1, apcsDB.size());
    }

    @isTest static void testAddApprenticesToApprenticeship(){

        Contact conLead = TestDataFactory.createContact();
        insert conLead;
        Apprenticeship__c aps1 = TestDataFactory.createApprenticeship(conLead);
        insert aps1;

        List<Apprentice__c> apcs1 = TestDataFactory.addApprenticesToApprenticeship(12, aps1);
        List<Apprentice__c> apcsDB = [SELECT Id FROM Apprentice__c];
        System.assertEquals(12, apcsDB.size());
    }

    @isTest static void testCreateGateway(){
        List<Gateway__c> gateways = new List<Gateway__c>();
        gateways.add(TestDataFactory.createGateway('WFT'));
        insert gateways;
        List<Gateway__c> gatewaysDB = [SELECT Id FROM Gateway__c];
        System.assertEquals(1,gatewaysDB.size());
    }

    @isTest static void testCreateAccount(){
        List<Account> accounts = new List<Account>();
        accounts.add(TestDataFactory.createAccount());
        insert accounts;
        List<Account> accountsDB = [SELECT Id FROM Account];
        System.assertEquals(1, accountsDB.size());
    }

    @isTest static void testCreateAccountWithRecordType(){
        List<Account> accounts = new List<Account>();
        accounts.add(TestDataFactory.createAccount('General'));
        insert accounts;
        List<Account> accountsDB = [SELECT Id FROM Account];
        System.assertEquals(1, accountsDB.size());
    }

    @isTest static void testCreateIndividualAccount(){
        List<Account> accounts = new List<Account>();
        accounts.add(TestDataFactory.createIndividualAccount());
        insert accounts;
        List<Account> accountsDB = [SELECT Id FROM Account];
        System.assertEquals(1, accountsDB.size());
    }

    @isTest static void testCreateMultipleAccounts(){
        List<Account> accounts = TestDataFactory.createMultipleAccounts(17,'BWRD');
        insert accounts;
        List<Account> accountsDB = [SELECT Id FROM Account];
        System.assertEquals(17, accountsDB.size());
    }

    @isTest static void testCreateOpportunity(){
        Account acc1 = TestDataFactory.createAccount();
        insert acc1;
        Contact con1 = TestDataFactory.createContact();
        insert con1;

        List<Opportunity> opps = new List<Opportunity>();
        opps.add(TestDataFactory.createOpportunity(acc1, con1));
        insert opps;
        List<Opportunity> oppsDB = [SELECT Id FROM Opportunity];
        System.assertEquals(1, oppsDB.size());
    }

    @isTest static void testCreateOpportunityWithRecordType(){
        Account acc1 = TestDataFactory.createAccount();
        insert acc1;
        Contact con1 = TestDataFactory.createContact();
        insert con1;

        List<Opportunity> opps = new List<Opportunity>();
        opps.add(TestDataFactory.createOpportunity(acc1, con1, 'BWTC'));
        insert opps;
        List<Opportunity> oppsDB = [SELECT Id FROM Opportunity];
        System.assertEquals(1, oppsDB.size());
    }

    @isTest static void testCreateMultipleOpportunities(){
        List<Opportunity> opps = TestDataFactory.createMultipleOpportunities(21,'BWRD');
        List<Opportunity> oppsDB = [SELECT Id FROM Opportunity];
        System.assertEquals(21, oppsDB.size());
    }

}