force-app/main/default/objects/Apprentice__c/Apprentice__c.object-meta.xml
<CustomObject>
    <label>Apprentice</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Apprentice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apprentices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Apprenticeship</label>
    <referenceTo>Apprenticeship__c</referenceTo>
    <relationshipLabel>Apprentices</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/Apprenticeship__c.object-meta.xml
<CustomObject>
    <label>Apprenticeship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Apprenticeship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apprenticeships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Career_Ready_Check__c/Career_Ready_Check__c.object-meta.xml
<CustomObject>
    <description>Created by BN
Geekwise Users 
Track Cohortian career readiness</description>
    <label>Career Ready Check</label>
    <nameField>
        <displayFormat>CRC-{0000}</displayFormat>
        <label>Career Ready Check ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Career Ready Checks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Career_Ready_Check__c/fields/Analytical_Notes__c.field-meta.xml
<CustomField>
    <fullName>Analytical_Notes__c</fullName>
    <description>Created by BN
For Geekwise Users
To track Cohortian career readiness</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Analytical Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Career_Ready_Check__c/fields/Apprentice__c.field-meta.xml
<CustomField>
    <fullName>Apprentice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by: JA
Purpose: Track Cohortian career readiness</description>
    <label>Apprentice</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Career Ready Checks</relationshipLabel>
    <relationshipName>Career_Ready_Checks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Career_Ready_Check__c/fields/Apprenticeship__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by: JA
Purpose: Track which Apprenticeship the CRC is for</description>
    <label>Apprenticeship</label>
    <referenceTo>Apprenticeship__c</referenceTo>
    <relationshipLabel>Career Ready Checks</relationshipLabel>
    <relationshipName>Career_Ready_Checks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Engagement__c/Student_Engagement__c.object-meta.xml
<CustomObject>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track Geekwise Student Interactions, Volunteering, etc.</description>
    <label>Student Engagement</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Student Engagement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Engagements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Engagement__c/fields/Engagement_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Notes__c</fullName>
    <description>Created By: BN
Business Unit: Geekwise Users
Purpose: To Track student engagements with Geekwise academy employees
Populated: Manually</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Engagement Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/WFTApprenticeshipRosterTests.cls
@isTest
public class WFTApprenticeshipRosterTests {
    @TestSetup
    static void makeData(){
        User adminUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator'  
        AND UserRole.Name = 'System Administrator' AND IsActive = true LIMIT 1];

        System.runAs ( adminUser ) {
        Contact currUserAsContact = new Contact(firstName = 'Contact', lastName = 'User111', email = 'currUserAsContact111@test.com', User__c = adminUser.Id);
            insert currUserAsContact;
        }

        Contact apprenticeLead = TestDataFactory.createContact();
        insert apprenticeLead;

        Apprenticeship__c apprenticeship1 = TestDataFactory.createApprenticeship(apprenticeLead);
        apprenticeship1.Name = 'test apprenticeship1';
        insert apprenticeship1;

        List<Apprentice__c> apprentices = TestDataFactory.addApprenticesToApprenticeship(3, apprenticeship1);
    }

    @isTest
    public static void getApprenticesTest() {
        WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
        Apprenticeship__c apprenticeship = [SELECT Id FROM Apprenticeship__c WHERE Name = 'test apprenticeship1'];

        c.apprenticeshipId = apprenticeship.Id;
        Test.startTest();
        c.getApprentices();
        Test.stopTest();

        System.assertEquals(c.apprentices.size(), 3);
    }
    
    @isTest
    static void showCareerReadyCheckTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
  
      Test.startTest();
      c.showCareerReadyCheck();
      Test.stopTest();
  
      System.AssertEquals(true, c.displayCareerReadyCheck);
    }

    @isTest 
    static void getUserContactIdTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
  
      contact contactUser = new contact(
        firstName = 'Contact1',
        lastName = 'User1',
        email = 'contactUser11@gmail.com',
        user__c = UserInfo.getUserId()
      );
      insert contactUser;
  
      Test.startTest();
      c.getUserContactId();
      Test.stopTest();
  
      System.assertEquals(contactUser.Id, c.currentUserContactId);
    }

    @isTest 
    static void saveCareerReadyCheckTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
      c.analyticalPicklistModal = '1';
      c.analyticalNoteTextModal = 'Analytical test';

      Test.startTest();
      c.saveCareerReadyCheck();
      Test.stopTest();

      Career_Ready_Check__c note = [SELECT Analytical_Notes__c FROM Career_Ready_Check__c LIMIT 1];
      System.AssertEquals('Analytical test', note.Analytical_Notes__c);
    }

    @isTest 
    static void saveNotesTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
      c.notes = 'Test notes';
  
      Test.startTest();
      c.saveNotes();
      Test.stopTest();
  
      Student_Engagement__c notes = [SELECT Engagement_Notes__c FROM Student_Engagement__c LIMIT 1];
      System.assertEquals('Test notes', notes.Engagement_Notes__c);
    }
  
    @isTest 
    static void saveNotesBlankTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
      c.notes = '';
  
      Test.startTest();
      c.saveNotes();
      Test.stopTest();
  
      list<Student_Engagement__c> notes = [SELECT Engagement_Notes__c FROM Student_Engagement__c];
      System.assertEquals(0, notes.size());
    }

    @isTest 
    static void showNotesTest() {
      WFTApprenticeshipRosterController c = new WFTApprenticeshipRosterController();
      
      Test.startTest();
      c.showNotes();
      Test.stopTest();
  
      System.assertEquals(true, c.displayNotes);
    }
  
}