force-app/main/default/objects/Apprentice__c/Apprentice__c.object-meta.xml
<CustomObject>
    <label>Apprentice</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Apprentice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apprentices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprentice__c/fields/Apprentice_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Apprentice_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apprentice Acceptance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Apprenticeship</label>
    <referenceTo>Apprenticeship__c</referenceTo>
    <relationshipLabel>Apprentices</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship_Lead__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
WFT
Is set by automation, used in email alerts.</description>
    <label>Apprenticeship Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprentices (Apprenticeship Lead)</relationshipLabel>
    <relationshipName>Apprentices_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprenticeships (Apprentice)</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Hourly_Wage__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Wage__c</fullName>
    <label>Hourly Wage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$17</fullName>
            </value>
            <value>
                <fullName>$20</fullName>
            </value>
            <value>
                <fullName>$22</fullName>
            </value>
            <value>
                <fullName>$25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created by JW
Business Unit: WFT
Tracks when this Apprentice started work for the Apprenticeship.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/Apprenticeship__c.object-meta.xml
<CustomObject>
    <label>Apprenticeship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Apprenticeship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apprenticeships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprenticeship__c/fields/Apprenticeship_Lead__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT
Keeps track of the Lead of this Apprenticeship.</description>
    <label>Apprenticeship Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprenticeships (Lead)</relationshipLabel>
    <relationshipName>Apprenticeships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Created by JW
Business Unit: WFT
Keeps track of the date this Apprenticeship begins.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WFTApprenticeAcceptanceController.cls
public class WFTApprenticeAcceptanceController {
    //Getting and setting the fields to be Queried
    public String appId{get; set;}
    public String appFirstName {get; set;}
    public String appLastName {get; set;}
    public String appName {get; set;}
    public String appWage {get; set;}
	 public String appLead {get; set;}
	public Date appStartDate {get; set;}
	public Boolean appAcceptance {get; set;}
    
    @TestVisible private Apprentice__c apprentice; 


   //start of the SQOL Query 
    public WFTApprenticeAcceptanceController() {
        appFirstName = '';
        appLastName = '';
        appName = '';
        appWage = '';
		appStartDate = null;
		appLead = '';
		appAcceptance = false;
        appId = apexpages.currentPage().getparameters().get('Id');
        GetApprentice();
        

    }

    public void GetApprentice() {
        List<Apprentice__c> apprentices = new List<Apprentice__c>(); 
        apprentices =[SELECT Id, Contact__r.FirstName, Contact__r.LastName, Apprenticeship__r.Name, Apprentice_Acceptance__c,Apprenticeship_Lead__r.Name, Hourly_Wage__c, Start_Date__c FROM Apprentice__c WHERE Id =: appId ];
        if ( apprentices.size() == 1 ) {
            apprentice = apprentices[0];
            appFirstName = apprentice.Contact__r.FirstName;
            appLastName = apprentice.Contact__r.LastName;
			appName = apprentice.Apprenticeship__r.Name;
			appWage = apprentice.Hourly_Wage__c;
			appStartDate = apprentice.Start_Date__c;
			appLead = apprentice.Apprenticeship_Lead__r.Name;
			appAcceptance = apprentice.Apprentice_Acceptance__c; 
        }
        else {
            System.debug(apprentices);
        }
    }
    
    public PageReference acceptApprenticeship() {
        if(apprentice.Id == null){
            return null;
        } 
        System.debug(apprentice);
		if(apprentice.Apprentice_Acceptance__c) {
			return null;
		}
		
		apprentice.Apprentice_Acceptance__c = true;
        
        Map<String, Object> apprenticeMap = new Map<String, Object>();
        apprenticeMap.put('id', apprentice.Id);
        apprenticeMap.put('acceptance', apprentice.Apprentice_Acceptance__c);
        String body = JSON.serialize(apprenticeMap);
        HttpRequest req = new HttpRequest();
        Http http = new Http();
        HttpResponse res = new HttpResponse();
        req.setEndpoint('https://hooks.zapier.com/hooks/catch/8857632/o7nh2ri/');
        req.setBody(body);
        req.setMethod('POST');
        res = http.send(req);
        System.debug(res);

        
        
		//update apprentice;
        return null;
    }

}