force-app/main/default/objects/Apprentice__c/Apprentice__c.object-meta.xml
<CustomObject>
    <label>Apprentice</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Apprentice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apprentices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprentice__c/fields/Apprentice_Acceptance__c.field-meta.xml
<CustomField>
    <fullName>Apprentice_Acceptance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apprentice Acceptance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Apprenticeship</label>
    <referenceTo>Apprenticeship__c</referenceTo>
    <relationshipLabel>Apprentices</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Apprenticeship_Lead__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
WFT
Is set by automation, used in email alerts.</description>
    <label>Apprenticeship Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprentices (Apprenticeship Lead)</relationshipLabel>
    <relationshipName>Apprentices_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprentice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprenticeships (Apprentice)</relationshipLabel>
    <relationshipName>Apprentices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apprenticeship__c/Apprenticeship__c.object-meta.xml
<CustomObject>
    <label>Apprenticeship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Apprenticeship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apprenticeships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apprenticeship__c/fields/Apprenticeship_Lead__c.field-meta.xml
<CustomField>
    <fullName>Apprenticeship_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created by JW
Business Unit: WFT
Keeps track of the Lead of this Apprenticeship.</description>
    <label>Apprenticeship Lead</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Apprenticeships (Lead)</relationshipLabel>
    <relationshipName>Apprenticeships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WFTApprenticeAcceptanceTests.cls
@istest
public class WFTApprenticeAcceptanceTests {
    @isTest
    public static void testGetApprentice() {
        Account acct = new Account(Name = 'Test Account');
        insert acct;
        Contact cont = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice',
                           LastName = 'Test Apprentice',
                           Email = 'testapp@test.com');
        insert cont;

        Contact contLead = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice Lead',
                           LastName = 'Test Apprentice Lead',
                           Email = 'testapplead@test.com');
        insert contLead;

        Apprenticeship__c app = new Apprenticeship__c(Name = 'Test Apprenticeship', Apprenticeship_Lead__c = contLead.Id);
        insert app;

        Apprentice__c apprentice = new Apprentice__c(Apprenticeship__c = app.Id, Contact__c = cont.Id);
        insert apprentice;

        WFTApprenticeAcceptanceController c = new WFTApprenticeAcceptanceController();
        c.appId = apprentice.Id;
        c.getApprentice();

        System.assertEquals(apprentice.Id,  c.apprentice.Id);

    }

    @isTest
    public static void testAcceptApprenticeship() {
        Account acct = new Account(Name = 'Test Account');
        insert acct;
        Contact cont = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice',
                           LastName = 'Test Apprentice',
                           Email = 'testapp@test.com');
        insert cont;

        Contact contLead = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice Lead',
                           LastName = 'Test Apprentice Lead',
                           Email = 'testapplead@test.com');
        insert contLead;

        Apprenticeship__c app = new Apprenticeship__c(Name = 'Test Apprenticeship', Apprenticeship_Lead__c = contLead.Id);
        insert app;

        Apprentice__c apprentice = new Apprentice__c(Apprenticeship__c = app.Id, Contact__c = cont.Id);
        insert apprentice;

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('WFTApprenticeAcceptanceMock');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

        Test.startTest();
        WFTApprenticeAcceptanceController c = new WFTApprenticeAcceptanceController();
        c.appId = apprentice.Id;
        c.getApprentice();
        c.acceptApprenticeship();
        Test.stopTest();
        System.assertEquals(true, c.apprentice.Apprentice_Acceptance__c = true);

    }
    
    @isTest
     public static void testAlreadyAcceptedApprenticeship() {
        Account acct = new Account(Name = 'Test Account');
        insert acct;
        Contact cont = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice',
                           LastName = 'Test Apprentice',
                           Email = 'testapp@test.com');
        insert cont;

        Contact contLead = new Contact(AccountId = acct.Id,
                           FirstName = 'Test Apprentice Lead',
                           LastName = 'Test Apprentice Lead',
                           Email = 'testapplead@test.com');
        insert contLead;

        Apprenticeship__c app = new Apprenticeship__c(Name = 'Test Apprenticeship', Apprenticeship_Lead__c = contLead.Id);
        insert app;

        Apprentice__c apprentice = new Apprentice__c(Apprenticeship__c = app.Id, Apprentice_Acceptance__c = true, Contact__c = cont.Id);
        insert apprentice;

        WFTApprenticeAcceptanceController c = new WFTApprenticeAcceptanceController();
        c.appId = apprentice.Id;
        c.getApprentice();
        c.acceptApprenticeship();
        Apprentice__c fromDatabase = [SELECT Id, Apprentice_Acceptance__c FROM Apprentice__c WHERE Id =: c.appId];

        System.assertEquals(true, fromDatabase.Apprentice_Acceptance__c);

    }
    
}