force-app/main/default/objects/Cowork_Custom_Settings__c/Cowork_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for the Cowork SMS Campaign Project</description>
    <label>Cowork Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Cowork_Custom_Settings__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <description>Email address will be sent an email when an error occurs.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Cowork_Custom_Settings__c/fields/Twilio_Account_SID__c.field-meta.xml
<CustomField>
    <fullName>Twilio_Account_SID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Twilio Account SID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cowork_Custom_Settings__c/fields/Twilio_API_Url__c.field-meta.xml
<CustomField>
    <fullName>Twilio_API_Url__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Twilio API Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cowork_Custom_Settings__c/fields/Twilio_Auth_Token__c.field-meta.xml
<CustomField>
    <fullName>Twilio_Auth_Token__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Twilio Auth Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Sent_SMS__c/Marketing_Sent_SMS__c.object-meta.xml
<CustomObject>
    <description>Sent message from a marketing sms push</description>
    <label>Marketing Sent SMS</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Marketing Sent SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Sent SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Sent_SMS__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that the message was sent to.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Sent SMS</relationshipLabel>
    <relationshipName>Marketing_Sent_SMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Sent_SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <description>Phone number that the message was sent from.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>From Phone</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Sent_SMS__c/fields/Marketing_SMS_Push__c.field-meta.xml
<CustomField>
    <fullName>Marketing_SMS_Push__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Marketing sms push that the message belonged to.</description>
    <label>Marketing SMS Push</label>
    <referenceTo>Marketing_SMS_Push__c</referenceTo>
    <relationshipLabel>Marketing Sent SMS</relationshipLabel>
    <relationshipName>Marketing_Sent_SMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Sent_SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <description>Phone number that the message was sent to.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>To Phone</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_SMS_Push__c/Marketing_SMS_Push__c.object-meta.xml
<CustomObject>
    <description>This obj will store the marketing push data for a marketing sms campaign.</description>
    <label>Marketing SMS Push</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Marketing SMS Push Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing SMS Pushes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_SMS_Push__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign the the sms push belongs to.</description>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Marketing SMS Pushes</relationshipLabel>
    <relationshipName>Marketing_SMS_Pushes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_SMS_Push__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>The message being sent out for the marketing sms campaign</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Content</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <description>Created by: RG
Business Unit: For Hashtag 
Purpose: To track memberships for clients</description>
    <label>Membership</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/IsExpired__c.field-meta.xml
<CustomField>
    <fullName>IsExpired__c</fullName>
    <formula>TODAY() &gt;  Membership_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsExpired (do not display)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CC Hashtag Membership Status Visualforce</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Active_Inactive</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CoworkSmsCampaignController.cls
public class CoworkSmsCampaignController {
    @AuraEnabled(cacheable=true)
    public static Integer getTotalContact() {
        return [SELECT Id FROM Membership__c WHERE (Status__c = 'Active' AND IsExpired__c = false AND (Contact__r.MobilePhone != null OR Contact__r.Phone != null))].size();
    }

    @AuraEnabled(cacheable=true)
    public static Marketing_SMS_Push__c[] getCoworkSmsCampaignPush() {
        List<Marketing_SMS_Push__c> msp = new List<Marketing_SMS_Push__c>();
 
        // Get Cowork campaign push object
        try {
	        Campaign campaign = [SELECT Id, Name, Type, Phone_Number__c, Keyword__c FROM Campaign WHERE Name='Cowork' LIMIT 1];
    	    msp = [SELECT Id, Campaign__c, Message_Content__c, (SELECT Id FROM Marketing_Sent_SMS__r) FROM Marketing_SMS_Push__c  WHERE Campaign__c = :campaign.Id ORDER BY CreatedDate DESC];
        } catch (Exception e) {
            System.debug('Error getting object data for Campaign Push');
            System.debug(e);
        }
        
        return msp;
    }

    @AuraEnabled(cacheable=false)
    @future(callout=true)
    public static void sendMessages(String smsContent) {
        String fromPhoneNumber, campaignId, twilioAPIUrl, twilioAccountSID, twilioAuthToken, supportEmail;
        Campaign campaign;
        List<Marketing_Sent_SMS__c> sentMessages = new List<Marketing_Sent_SMS__c>();
        
        // Get Cowork campaign object
        try {
        	campaign = [SELECT Id, Name, Type, Phone_Number__c, Keyword__c FROM Campaign WHERE Name='Cowork' LIMIT 1];
            fromPhoneNumber = campaign.Phone_Number__c;
            campaignId = campaign.Id;    
        } catch (Exception e) {
            System.debug('Error getting Cowork SMS Campaign to send message.');
            System.debug(e);
            return;
        }

        // Get Cowork custom settings
        try {
            Cowork_custom_settings__c settings = Cowork_custom_settings__c.getOrgDefaults();
            twilioAPIUrl = settings.Twilio_API_Url__c;
            twilioAccountSID = settings.Twilio_Account_SID__c;
            twilioAuthToken = settings.Twilio_Auth_Token__c;
            supportEmail = settings.Support_Email__c ;
            
        } catch (Exception e) {
            System.debug('Error getting Cowork custom settings to send message.');
            System.debug(e);
            return;
        }
        
        // Check for campaign phone number
        if (String.isBlank(fromPhoneNumber)) {            
            System.debug('Campaign phone number is missing');
            System.debug(campaign);
            return;
        }
        
        // Check for valid custom setting variables
        if (String.isBlank(twilioApiUrl)) (System.debug('twilioApiUrl custom setting variable is missing'));
        if (String.isBlank(twilioAccountSID)) (System.debug('twilioAccountSID custom setting variable is missing'));
        if (String.isBlank(twilioAuthToken)) (System.debug('twilioAuthToken custom setting variable is missing'));
        
        if (String.isBlank(twilioAPIUrl) || String.isBlank(twilioAccountSID) || String.isBlank(twilioAuthToken)) {
            return;
        }
        
        // Loop through all non-expired memberships
        for (Membership__c membership : [SELECT Id, IsExpired__c, Contact__r.Id, Contact__r.Name, Contact__r.MobilePhone, Contact__r.Phone FROM Membership__c WHERE (Status__c = 'Active' AND IsExpired__c = false AND (Contact__r.MobilePhone != null OR Contact__r.Phone != null))]) {
            // Grab Phone Number from contact from either the MobilePhone or Phone field
            String phoneNumber = membership.Contact__r.MobilePhone;
            
            if (String.isBlank(phoneNumber)) {
                phoneNumber = membership.Contact__r.Phone;
            }
            
            // Check that membership's contact has a phone number
            if (!String.isBlank(phoneNumber)) {
                // Format phone number
                String toPhoneNumber = phoneNumber.replaceAll('[^0-9]', '');
                    
                if (toPhoneNumber.length() > 10) {
                    toPhoneNumber = toPhoneNumber.right(10);
                }
                
                toPhoneNumber = '+1' + toPhoneNumber;
                
                // Send request to Twilio to send message
                HttpRequest req = new HttpRequest();
                req.setEndpoint(twilioAPIUrl);
                req.setMethod('POST');
                
                Blob headerValue = Blob.valueOf(twilioAccountSID + ':' + twilioAuthToken);
                String authorizationHeader = 'Basic ' +
                    EncodingUtil.base64Encode(headerValue);
                req.setHeader('Authorization', authorizationHeader);                
                
                String payload = 'From='+EncodingUtil.urlEncode(fromPhoneNumber,'UTF-8')+'&To='+EncodingUtil.urlEncode(toPhoneNumber,'UTF-8')+'&Body='+EncodingUtil.urlEncode(smsContent,'UTF-8');
                req.setBody(payload);
                Http http = new Http();
                HTTPResponse res = http.send(req);
                
				// Check if Twilio accepted sending message request
                if (res.getStatusCode() == 201) {
                    Marketing_Sent_SMS__c  mss = new Marketing_Sent_SMS__c  (
                        Contact__c = membership.Contact__r.Id,
                        To_Phone__c = toPhoneNumber,
                        From_Phone__c = fromPhoneNumber
                    );
                    
                    sentMessages.add(mss);
                } else {
                    System.debug('Error sending message with Twilio.');
                    System.debug(membership);
                }
            }
        }

        // Create all object entries
        // Must be done after sending http requests due to SF restrictions
        Marketing_SMS_Push__c msp = new Marketing_SMS_Push__c (
        	Message_Content__c = smsContent,
            Campaign__c = campaignId
        );
        
        insert msp;        
        
        for (Marketing_Sent_SMS__c mss : sentMessages) {
            mss.Marketing_SMS_Push__c = msp.Id;
        }
        
        insert sentMessages;
    }
}