force-app/main/default/objects/Lease_Space__c/Lease_Space__c.object-meta.xml
<CustomObject>
    <label>Lease Space</label>
    <nameField>
        <displayFormat>LS-{0000000}</displayFormat>
        <label>Lease Space Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Space__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipName>Lease_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeasingHelper.cls
public class LeasingHelper {
        @InvocableMethod
		public static List<List<Space__c>> getSpacesFromLeaseSpaces(List<List<Lease_Space__c>> leaseSpaces) {
            List<Id> spaceIds = new List<Id> ();
            List<Lease_Space__c> leaseSpaceSingleList = new List<Lease_Space__c>();
            leaseSpaceSingleList = leaseSpaces[0];
            for (Lease_Space__c singleLeaseSpace : leaseSpaceSingleList) {
                spaceIds.add(singleLeaseSpace.Space__c);
            }
            List<Space__c> relatedSpacesSingleList = new List <Space__c>();
            relatedSpacesSingleList = [SELECT Id FROM Space__c WHERE Id IN :spaceIds];
            List<List<Space__c>> relatedSpaces =  new List<List<Space__c>>();
            relatedSpaces.add(relatedSpacesSingleList);
            return relatedSpaces;
        }
}