force-app/main/default/objects/Lease_Space__c/Lease_Space__c.object-meta.xml
<CustomObject>
    <label>Lease Space</label>
    <nameField>
        <displayFormat>LS-{0000000}</displayFormat>
        <label>Lease Space Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Space__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Lease Spaces</relationshipLabel>
    <relationshipName>Lease_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lease_Space__c/fields/Space__c.field-meta.xml
<CustomField>
    <fullName>Space__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Space</label>
    <referenceTo>Space__c</referenceTo>
    <relationshipName>Lease_Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Space__c/Space__c.object-meta.xml
<CustomObject>
    <description>The spaces that exist within Bitwise Industries (i.e buildings and rooms within)</description>
    <label>Space</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Space__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of a given space</description>
    <inlineHelpText>What is the status of the space?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeasingHelperTest.cls
@isTest
public class LeasingHelperTest {
	
	@isTest
    public static void testLeaseSpaces() {
      
        Space__c spa = new Space__c(Name = 'Test', Status__c = 'New'); 
	   insert spa;

	   Account acc = new Account(Name = 'testAcc');
	   insert acc;

	   Contact con = new Contact(AccountId = acc.Id, LastName = 'Tester');
	   insert con;

	   Opportunity opp = new Opportunity(Name = 'testOpp', AccountId = acc.Id, Industry__c = 'Media', 
						 CloseDate = date.today(), StageName = 'New', ForecastCategoryName = 'Omitted', 
						 Primary_Contact__c = con.Id);
	   insert opp;

	   Lease_Space__c leaseSpace = new Lease_Space__c(Opportunity__c = Opp.Id, Space__c = spa.Id);		
	   insert leaseSpace;
	
	   List<Lease_Space__c> leaseList = new List<Lease_Space__c>();
       leaseList.add(leaseSpace);
       
       List<List<Lease_Space__c>> leaseSpaceWrapper = new List<List<Lease_Space__c>>();
       leaseSpaceWrapper.add(leaseList);
        
       List<List<Space__c>> spaceWrapper = LeasingHelper.getSpacesFromLeaseSpaces(leaseSpaceWrapper);
   
       
       System.assertEquals(spa.Id, spaceWrapper[0].get(0).Id);
    }
}